// Turbo Drive texts.

import { addStrings } from '../../shared/i18n.js';

addStrings({
  en: {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Driving view',
    'drive.loading': 'Building the track…',
    'drive.where': 'Where to?',
    'drive.scenario.city': 'Neon City',
    'drive.scenario.jungle': 'Jungle',
    'drive.scenario.wasteland': 'Wasteland',
    'drive.scenarioBlurb.city': 'Gold coins under neon lights',
    'drive.scenarioBlurb.jungle': 'Emeralds among ancient temples',
    'drive.scenarioBlurb.wasteland': 'Gears in the snow, then the desert',
    'drive.car': 'Your car',
    'drive.car.comet': 'Comet',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Paint',
    'drive.paintColor': 'Paint color {number}',
    'drive.level': 'Level',
    'drive.difficulty.easy': 'Easy',
    'drive.difficulty.medium': 'Medium',
    'drive.difficulty.hard': 'Hard',
    'drive.difficultyBlurb.easy': 'Points in the middle of the road',
    'drive.difficultyBlurb.medium': 'Points from side to side',
    'drive.difficultyBlurb.hard': 'Points at the edges and in the bends',
    'drive.go': 'Drive!',
    'drive.best': 'Best: {time}',
    'drive.noBest': 'No best time yet',
    'drive.points': 'Points',
    'drive.time': 'Time',
    'drive.lap': 'Lap {lap}',
    'drive.nitro': 'Nitro',
    'drive.brake': 'Brake',
    'drive.left': 'Steer left',
    'drive.right': 'Steer right',
    'drive.pause': 'Pause',
    'drive.paused': 'Paused',
    'drive.resume': 'Keep driving',
    'drive.restart': 'Start over',
    'drive.change': 'Change car or track',
    'drive.countGo': 'GO!',
    'drive.collectAll': 'Collect all the points!',
    'drive.wrongWay': 'Wrong way! Turn around',
    'drive.finishTitle': 'All points collected!',
    'drive.finishTime': 'Time: {time}',
    'drive.newBest': 'New best time!',
    'drive.again': 'Drive again',
    'drive.keys': 'Arrows or A and D to steer · Space for nitro · Down or S to brake',
    'drive.pointsLeft': { one: '{count} point left', other: '{count} points left' },
  },
  it: {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Vista di guida',
    'drive.loading': 'Sto costruendo la pista…',
    'drive.where': 'Dove andiamo?',
    'drive.scenario.city': 'Città al neon',
    'drive.scenario.jungle': 'Giungla',
    'drive.scenario.wasteland': 'Terre desolate',
    'drive.scenarioBlurb.city': 'Monete d’oro sotto le luci al neon',
    'drive.scenarioBlurb.jungle': 'Smeraldi tra templi antichi',
    'drive.scenarioBlurb.wasteland': 'Ingranaggi nella neve, poi nel deserto',
    'drive.car': 'La tua auto',
    'drive.car.comet': 'Cometa',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Colore',
    'drive.paintColor': 'Colore {number}',
    'drive.level': 'Livello',
    'drive.difficulty.easy': 'Facile',
    'drive.difficulty.medium': 'Medio',
    'drive.difficulty.hard': 'Difficile',
    'drive.difficultyBlurb.easy': 'Punti in mezzo alla strada',
    'drive.difficultyBlurb.medium': 'Punti da un lato all’altro',
    'drive.difficultyBlurb.hard': 'Punti sui bordi e nelle curve',
    'drive.go': 'Si parte!',
    'drive.best': 'Record: {time}',
    'drive.noBest': 'Ancora nessun record',
    'drive.points': 'Punti',
    'drive.time': 'Tempo',
    'drive.lap': 'Giro {lap}',
    'drive.nitro': 'Nitro',
    'drive.brake': 'Freno',
    'drive.left': 'Sterza a sinistra',
    'drive.right': 'Sterza a destra',
    'drive.pause': 'Pausa',
    'drive.paused': 'In pausa',
    'drive.resume': 'Continua a guidare',
    'drive.restart': 'Ricomincia',
    'drive.change': 'Cambia auto o pista',
    'drive.countGo': 'VIA!',
    'drive.collectAll': 'Raccogli tutti i punti!',
    'drive.wrongWay': 'Senso sbagliato! Gira la macchina',
    'drive.finishTitle': 'Tutti i punti raccolti!',
    'drive.finishTime': 'Tempo: {time}',
    'drive.newBest': 'Nuovo record!',
    'drive.again': 'Guida ancora',
    'drive.keys': 'Frecce o A e D per sterzare · Spazio per il nitro · Giù o S per frenare',
    'drive.pointsLeft': { one: 'Manca {count} punto', other: 'Mancano {count} punti' },
  },
  es: {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Vista de conducción',
    'drive.loading': 'Construyendo la pista…',
    'drive.where': '¿Adónde vamos?',
    'drive.scenario.city': 'Ciudad neón',
    'drive.scenario.jungle': 'Selva',
    'drive.scenario.wasteland': 'Tierra baldía',
    'drive.scenarioBlurb.city': 'Monedas de oro bajo luces de neón',
    'drive.scenarioBlurb.jungle': 'Esmeraldas entre templos antiguos',
    'drive.scenarioBlurb.wasteland': 'Engranajes en la nieve y luego en el desierto',
    'drive.car': 'Tu coche',
    'drive.car.comet': 'Cometa',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Pintura',
    'drive.paintColor': 'Color {number}',
    'drive.level': 'Nivel',
    'drive.difficulty.easy': 'Fácil',
    'drive.difficulty.medium': 'Medio',
    'drive.difficulty.hard': 'Difícil',
    'drive.difficultyBlurb.easy': 'Puntos en el centro de la carretera',
    'drive.difficultyBlurb.medium': 'Puntos de un lado a otro',
    'drive.difficultyBlurb.hard': 'Puntos en los bordes y en las curvas',
    'drive.go': '¡A conducir!',
    'drive.best': 'Récord: {time}',
    'drive.noBest': 'Aún no hay récord',
    'drive.points': 'Puntos',
    'drive.time': 'Tiempo',
    'drive.lap': 'Vuelta {lap}',
    'drive.nitro': 'Nitro',
    'drive.brake': 'Freno',
    'drive.left': 'Girar a la izquierda',
    'drive.right': 'Girar a la derecha',
    'drive.pause': 'Pausa',
    'drive.paused': 'En pausa',
    'drive.resume': 'Seguir conduciendo',
    'drive.restart': 'Empezar de nuevo',
    'drive.change': 'Cambiar coche o pista',
    'drive.countGo': '¡YA!',
    'drive.collectAll': '¡Recoge todos los puntos!',
    'drive.wrongWay': '¡Sentido contrario! Da la vuelta',
    'drive.finishTitle': '¡Todos los puntos recogidos!',
    'drive.finishTime': 'Tiempo: {time}',
    'drive.newBest': '¡Nuevo récord!',
    'drive.again': 'Conducir otra vez',
    'drive.keys': 'Flechas o A y D para girar · Espacio para el nitro · Abajo o S para frenar',
    'drive.pointsLeft': { one: 'Queda {count} punto', other: 'Quedan {count} puntos' },
  },
  'pt-BR': {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Visão de direção',
    'drive.loading': 'Construindo a pista…',
    'drive.where': 'Para onde vamos?',
    'drive.scenario.city': 'Cidade neon',
    'drive.scenario.jungle': 'Selva',
    'drive.scenario.wasteland': 'Terra devastada',
    'drive.scenarioBlurb.city': 'Moedas de ouro sob luzes de neon',
    'drive.scenarioBlurb.jungle': 'Esmeraldas entre templos antigos',
    'drive.scenarioBlurb.wasteland': 'Engrenagens na neve e depois no deserto',
    'drive.car': 'Seu carro',
    'drive.car.comet': 'Cometa',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Pintura',
    'drive.paintColor': 'Cor {number}',
    'drive.level': 'Nível',
    'drive.difficulty.easy': 'Fácil',
    'drive.difficulty.medium': 'Médio',
    'drive.difficulty.hard': 'Difícil',
    'drive.difficultyBlurb.easy': 'Pontos no meio da pista',
    'drive.difficultyBlurb.medium': 'Pontos de um lado para o outro',
    'drive.difficultyBlurb.hard': 'Pontos nas beiradas e nas curvas',
    'drive.go': 'Acelerar!',
    'drive.best': 'Recorde: {time}',
    'drive.noBest': 'Ainda sem recorde',
    'drive.points': 'Pontos',
    'drive.time': 'Tempo',
    'drive.lap': 'Volta {lap}',
    'drive.nitro': 'Nitro',
    'drive.brake': 'Freio',
    'drive.left': 'Virar à esquerda',
    'drive.right': 'Virar à direita',
    'drive.pause': 'Pausar',
    'drive.paused': 'Pausado',
    'drive.resume': 'Continuar dirigindo',
    'drive.restart': 'Começar de novo',
    'drive.change': 'Trocar carro ou pista',
    'drive.countGo': 'JÁ!',
    'drive.collectAll': 'Pegue todos os pontos!',
    'drive.wrongWay': 'Contramão! Dê a volta',
    'drive.finishTitle': 'Todos os pontos coletados!',
    'drive.finishTime': 'Tempo: {time}',
    'drive.newBest': 'Novo recorde!',
    'drive.again': 'Dirigir de novo',
    'drive.keys': 'Setas ou A e D para virar · Espaço para o nitro · Para baixo ou S para frear',
    'drive.pointsLeft': { one: 'Falta {count} ponto', other: 'Faltam {count} pontos' },
  },
  de: {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Fahransicht',
    'drive.loading': 'Die Strecke wird gebaut…',
    'drive.where': 'Wohin geht’s?',
    'drive.scenario.city': 'Neonstadt',
    'drive.scenario.jungle': 'Dschungel',
    'drive.scenario.wasteland': 'Ödland',
    'drive.scenarioBlurb.city': 'Goldmünzen unter Neonlichtern',
    'drive.scenarioBlurb.jungle': 'Smaragde zwischen alten Tempeln',
    'drive.scenarioBlurb.wasteland': 'Zahnräder im Schnee, dann in der Wüste',
    'drive.car': 'Dein Auto',
    'drive.car.comet': 'Komet',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Lack',
    'drive.paintColor': 'Farbe {number}',
    'drive.level': 'Stufe',
    'drive.difficulty.easy': 'Leicht',
    'drive.difficulty.medium': 'Mittel',
    'drive.difficulty.hard': 'Schwer',
    'drive.difficultyBlurb.easy': 'Punkte mitten auf der Straße',
    'drive.difficultyBlurb.medium': 'Punkte mal links, mal rechts',
    'drive.difficultyBlurb.hard': 'Punkte am Rand und in den Kurven',
    'drive.go': 'Losfahren!',
    'drive.best': 'Bestzeit: {time}',
    'drive.noBest': 'Noch keine Bestzeit',
    'drive.points': 'Punkte',
    'drive.time': 'Zeit',
    'drive.lap': 'Runde {lap}',
    'drive.nitro': 'Nitro',
    'drive.brake': 'Bremse',
    'drive.left': 'Nach links lenken',
    'drive.right': 'Nach rechts lenken',
    'drive.pause': 'Pause',
    'drive.paused': 'Pause',
    'drive.resume': 'Weiterfahren',
    'drive.restart': 'Neu starten',
    'drive.change': 'Auto oder Strecke wechseln',
    'drive.countGo': 'LOS!',
    'drive.collectAll': 'Sammle alle Punkte!',
    'drive.wrongWay': 'Falsche Richtung! Dreh um',
    'drive.finishTitle': 'Alle Punkte gesammelt!',
    'drive.finishTime': 'Zeit: {time}',
    'drive.newBest': 'Neue Bestzeit!',
    'drive.again': 'Nochmal fahren',
    'drive.keys': 'Pfeile oder A und D zum Lenken · Leertaste für Nitro · Runter oder S zum Bremsen',
    'drive.pointsLeft': { one: 'Noch {count} Punkt', other: 'Noch {count} Punkte' },
  },
});
