// Turbo Drive texts.

import { addStrings } from '../../shared/i18n.js';

addStrings({
  en: {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Driving view',
    'drive.loading': 'Building the track…',
    'drive.where': 'Where to?',
    'drive.scenario.city': 'Neon City',
    'drive.scenario.jungle': 'Jungle',
    'drive.scenario.wasteland': 'Wasteland',
    'drive.scenarioBlurb.city': 'Gold coins under neon lights',
    'drive.scenarioBlurb.jungle': 'Emeralds among ancient temples',
    'drive.scenarioBlurb.wasteland': 'Gears in the snow, then the desert',
    'drive.car': 'Your car',
    'drive.car.comet': 'Comet',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Paint',
    'drive.music': 'Music',
    'drive.musicOn': 'Music is on. Turn music off',
    'drive.musicOff': 'Music is off. Turn music on',
    'drive.myTracks': 'My tracks',
    'drive.buildTrack': '+ Build a track',
    'drive.editTrack': 'Edit this track',
    'drive.builder': 'Track builder',
    'drive.closeBuilder': 'Close the track builder',
    'drive.trackMap': 'Your track, seen from above',
    'drive.pieces': 'Road pieces',
    'drive.straight': 'Straight',
    'drive.curveLeft': 'Curve left',
    'drive.curveRight': 'Curve right',
    'drive.undo': 'Undo',
    'drive.clearTrack': 'Clear',
    'drive.trackName': 'Track name',
    'drive.defaultName': 'My track',
    'drive.trackLook': 'Scenery',
    'drive.tryTrack': 'Save and drive',
    'drive.saveTrack': 'Save',
    'drive.trackSaved': 'Saved!',
    'drive.export': 'Export',
    'drive.copyCode': 'Copy code',
    'drive.copied': 'Track code copied! Paste it anywhere to share.',
    'drive.import': 'Import',
    'drive.importHelp': 'Paste a track code, or choose a track file.',
    'drive.importCode': 'Track code',
    'drive.loadCode': 'Load',
    'drive.chooseFile': 'Choose file',
    'drive.importFailed': 'That isn’t a Playbox track.',
    'drive.imported': 'Track loaded! Save it to keep it.',
    'drive.deleteTrack': 'Delete',
    'drive.deleteConfirm': 'Tap again to delete',
    'drive.track.empty': 'Add road pieces. The dashed road joins the end back to the start by itself.',
    'drive.track.short': 'A bit short: add more road.',
    'drive.track.tight': 'The way back to the start is too tight (red circle). Add more turns toward the start.',
    'drive.track.crossing': 'The road runs into itself (red circle). Try a different turn.',
    'drive.track.ok': 'Ready to drive! {length} long.',
    'drive.paintColor': 'Paint color {number}',
    'drive.customize': 'Customize',
    'drive.presets': 'Street racer looks',
    'drive.preset.muscle': 'Midnight Muscle',
    'drive.preset.silverGt': 'Silver Street GT',
    'drive.preset.limeTuner': 'Lime Tuner',
    'drive.preset.orangeRocket': 'Orange Rocket',
    'drive.preset.neonPink': 'Neon Pink',
    'drive.custom.decal': 'Side graphics',
    'drive.decal.none': 'None',
    'drive.decal.swirl': 'Swooshes',
    'drive.decal.tribal': 'Tribal',
    'drive.decal.flames': 'Flames',
    'drive.custom.decalColor': 'Graphics color',
    'drive.custom.hood': 'Hood',
    'drive.hood.none': 'Plain',
    'drive.hood.scoop': 'Scoop',
    'drive.hood.blower': 'Supercharger',
    'drive.custom.finish': 'Finish',
    'drive.finish.gloss': 'Glossy',
    'drive.finish.matte': 'Matte',
    'drive.finish.chrome': 'Chrome',
    'drive.custom.stripes': 'Stripes',
    'drive.stripes.none': 'None',
    'drive.stripes.single': 'One',
    'drive.stripes.double': 'Two',
    'drive.custom.stripeColor': 'Stripe color',
    'drive.custom.rims': 'Wheels',
    'drive.rims.silver': 'Silver',
    'drive.rims.black': 'Black',
    'drive.rims.gold': 'Gold',
    'drive.rims.red': 'Red',
    'drive.custom.wing': 'Wing',
    'drive.wing.auto': 'Standard',
    'drive.wing.none': 'None',
    'drive.wing.small': 'Small',
    'drive.wing.big': 'Big',
    'drive.custom.glow': 'Underglow',
    'drive.glow.auto': 'At night',
    'drive.glow.off': 'Off',
    'drive.colorChoice': 'Color {number}',
    'drive.steering': 'Steering',
    'drive.control.buttons': 'Buttons',
    'drive.control.tilt': 'Tilt the phone',
    'drive.tiltNote': 'Hold the phone like a steering wheel and tilt it to turn.',
    'drive.tiltDenied': 'Motion access wasn’t allowed, so the buttons are back. You can allow it in the browser settings.',
    'drive.tiltHint': 'Tilt to steer! Tap the screen to straighten up.',
    'drive.level': 'Level',
    'drive.difficulty.easy': 'Easy',
    'drive.difficulty.medium': 'Medium',
    'drive.difficulty.hard': 'Hard',
    'drive.difficultyBlurb.easy': 'Points in the middle of the road',
    'drive.difficultyBlurb.medium': 'Points from side to side',
    'drive.difficultyBlurb.hard': 'Points at the edges and in the bends',
    'drive.go': 'Drive!',
    'drive.best': 'Best: {time}',
    'drive.noBest': 'No best time yet',
    'drive.points': 'Points',
    'drive.time': 'Time',
    'drive.lap': 'Lap {lap}',
    'drive.left': 'Steer left',
    'drive.right': 'Steer right',
    'drive.pause': 'Pause',
    'drive.paused': 'Paused',
    'drive.resume': 'Keep driving',
    'drive.restart': 'Start over',
    'drive.change': 'Change car or track',
    'drive.countGo': 'GO!',
    'drive.collectAll': 'Collect all the points!',
    'drive.wrongWay': 'Wrong way! Turn around',
    'drive.finishTitle': 'All points collected!',
    'drive.finishTime': 'Time: {time}',
    'drive.newBest': 'New best time!',
    'drive.again': 'Drive again',
    'drive.keys': 'Arrows or A and D to steer · Drive over the blue arrows for a boost',
    'drive.pointsLeft': { one: '{count} point left', other: '{count} points left' },
  },
  it: {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Vista di guida',
    'drive.loading': 'Sto costruendo la pista…',
    'drive.where': 'Dove andiamo?',
    'drive.scenario.city': 'Città al neon',
    'drive.scenario.jungle': 'Giungla',
    'drive.scenario.wasteland': 'Terre desolate',
    'drive.scenarioBlurb.city': 'Monete d’oro sotto le luci al neon',
    'drive.scenarioBlurb.jungle': 'Smeraldi tra templi antichi',
    'drive.scenarioBlurb.wasteland': 'Ingranaggi nella neve, poi nel deserto',
    'drive.car': 'La tua auto',
    'drive.car.comet': 'Cometa',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Colore',
    'drive.music': 'Musica',
    'drive.musicOn': 'Musica accesa. Spegni la musica',
    'drive.musicOff': 'Musica spenta. Accendi la musica',
    'drive.myTracks': 'Le mie piste',
    'drive.buildTrack': '+ Costruisci una pista',
    'drive.editTrack': 'Modifica questa pista',
    'drive.builder': 'Costruttore di piste',
    'drive.closeBuilder': 'Chiudi il costruttore di piste',
    'drive.trackMap': 'La tua pista vista dall’alto',
    'drive.pieces': 'Pezzi di strada',
    'drive.straight': 'Rettilineo',
    'drive.curveLeft': 'Curva a sinistra',
    'drive.curveRight': 'Curva a destra',
    'drive.undo': 'Annulla',
    'drive.clearTrack': 'Cancella',
    'drive.trackName': 'Nome della pista',
    'drive.defaultName': 'La mia pista',
    'drive.trackLook': 'Paesaggio',
    'drive.tryTrack': 'Salva e guida',
    'drive.saveTrack': 'Salva',
    'drive.trackSaved': 'Salvata!',
    'drive.export': 'Esporta',
    'drive.copyCode': 'Copia codice',
    'drive.copied': 'Codice della pista copiato! Incollalo dove vuoi per condividerla.',
    'drive.import': 'Importa',
    'drive.importHelp': 'Incolla un codice pista o scegli un file pista.',
    'drive.importCode': 'Codice pista',
    'drive.loadCode': 'Carica',
    'drive.chooseFile': 'Scegli file',
    'drive.importFailed': 'Questa non è una pista di Playbox.',
    'drive.imported': 'Pista caricata! Salvala per tenerla.',
    'drive.deleteTrack': 'Elimina',
    'drive.deleteConfirm': 'Tocca ancora per eliminare',
    'drive.track.empty': 'Aggiungi pezzi di strada. La strada tratteggiata riporta da sola la fine all’inizio.',
    'drive.track.short': 'Un po’ corta: aggiungi altra strada.',
    'drive.track.tight': 'Il ritorno all’inizio è troppo stretto (cerchio rosso). Aggiungi curve verso la partenza.',
    'drive.track.crossing': 'La strada va a sbattere contro se stessa (cerchio rosso). Prova un’altra curva.',
    'drive.track.ok': 'Pronta da guidare! Lunga {length}.',
    'drive.paintColor': 'Colore {number}',
    'drive.customize': 'Personalizza',
    'drive.presets': 'Stili da corsa su strada',
    'drive.preset.muscle': 'Muscolo di mezzanotte',
    'drive.preset.silverGt': 'GT argento',
    'drive.preset.limeTuner': 'Tuner lime',
    'drive.preset.orangeRocket': 'Razzo arancione',
    'drive.preset.neonPink': 'Rosa neon',
    'drive.custom.decal': 'Grafiche laterali',
    'drive.decal.none': 'Nessuna',
    'drive.decal.swirl': 'Onde',
    'drive.decal.tribal': 'Tribali',
    'drive.decal.flames': 'Fiamme',
    'drive.custom.decalColor': 'Colore grafiche',
    'drive.custom.hood': 'Cofano',
    'drive.hood.none': 'Liscio',
    'drive.hood.scoop': 'Presa d’aria',
    'drive.hood.blower': 'Compressore',
    'drive.custom.finish': 'Vernice',
    'drive.finish.gloss': 'Lucida',
    'drive.finish.matte': 'Opaca',
    'drive.finish.chrome': 'Cromata',
    'drive.custom.stripes': 'Strisce',
    'drive.stripes.none': 'Nessuna',
    'drive.stripes.single': 'Una',
    'drive.stripes.double': 'Due',
    'drive.custom.stripeColor': 'Colore strisce',
    'drive.custom.rims': 'Cerchi',
    'drive.rims.silver': 'Argento',
    'drive.rims.black': 'Neri',
    'drive.rims.gold': 'Oro',
    'drive.rims.red': 'Rossi',
    'drive.custom.wing': 'Alettone',
    'drive.wing.auto': 'Di serie',
    'drive.wing.none': 'Nessuno',
    'drive.wing.small': 'Piccolo',
    'drive.wing.big': 'Grande',
    'drive.custom.glow': 'Luci sotto',
    'drive.glow.auto': 'Di notte',
    'drive.glow.off': 'Spente',
    'drive.colorChoice': 'Colore {number}',
    'drive.steering': 'Sterzo',
    'drive.control.buttons': 'Pulsanti',
    'drive.control.tilt': 'Inclina il telefono',
    'drive.tiltNote': 'Tieni il telefono come un volante e inclinalo per girare.',
    'drive.tiltDenied': 'L’accesso al movimento non è stato permesso, quindi tornano i pulsanti. Puoi permetterlo nelle impostazioni del browser.',
    'drive.tiltHint': 'Inclina per sterzare! Tocca lo schermo per raddrizzare.',
    'drive.level': 'Livello',
    'drive.difficulty.easy': 'Facile',
    'drive.difficulty.medium': 'Medio',
    'drive.difficulty.hard': 'Difficile',
    'drive.difficultyBlurb.easy': 'Punti in mezzo alla strada',
    'drive.difficultyBlurb.medium': 'Punti da un lato all’altro',
    'drive.difficultyBlurb.hard': 'Punti sui bordi e nelle curve',
    'drive.go': 'Si parte!',
    'drive.best': 'Record: {time}',
    'drive.noBest': 'Ancora nessun record',
    'drive.points': 'Punti',
    'drive.time': 'Tempo',
    'drive.lap': 'Giro {lap}',
    'drive.left': 'Sterza a sinistra',
    'drive.right': 'Sterza a destra',
    'drive.pause': 'Pausa',
    'drive.paused': 'In pausa',
    'drive.resume': 'Continua a guidare',
    'drive.restart': 'Ricomincia',
    'drive.change': 'Cambia auto o pista',
    'drive.countGo': 'VIA!',
    'drive.collectAll': 'Raccogli tutti i punti!',
    'drive.wrongWay': 'Senso sbagliato! Gira la macchina',
    'drive.finishTitle': 'Tutti i punti raccolti!',
    'drive.finishTime': 'Tempo: {time}',
    'drive.newBest': 'Nuovo record!',
    'drive.again': 'Guida ancora',
    'drive.keys': 'Frecce o A e D per sterzare · Passa sulle frecce blu per un turbo',
    'drive.pointsLeft': { one: 'Manca {count} punto', other: 'Mancano {count} punti' },
  },
  es: {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Vista de conducción',
    'drive.loading': 'Construyendo la pista…',
    'drive.where': '¿Adónde vamos?',
    'drive.scenario.city': 'Ciudad neón',
    'drive.scenario.jungle': 'Selva',
    'drive.scenario.wasteland': 'Tierra baldía',
    'drive.scenarioBlurb.city': 'Monedas de oro bajo luces de neón',
    'drive.scenarioBlurb.jungle': 'Esmeraldas entre templos antiguos',
    'drive.scenarioBlurb.wasteland': 'Engranajes en la nieve y luego en el desierto',
    'drive.car': 'Tu coche',
    'drive.car.comet': 'Cometa',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Pintura',
    'drive.music': 'Música',
    'drive.musicOn': 'Música activada. Quitar la música',
    'drive.musicOff': 'Música desactivada. Poner la música',
    'drive.myTracks': 'Mis pistas',
    'drive.buildTrack': '+ Construir una pista',
    'drive.editTrack': 'Editar esta pista',
    'drive.builder': 'Constructor de pistas',
    'drive.closeBuilder': 'Cerrar el constructor de pistas',
    'drive.trackMap': 'Tu pista vista desde arriba',
    'drive.pieces': 'Piezas de carretera',
    'drive.straight': 'Recta',
    'drive.curveLeft': 'Curva a la izquierda',
    'drive.curveRight': 'Curva a la derecha',
    'drive.undo': 'Deshacer',
    'drive.clearTrack': 'Borrar',
    'drive.trackName': 'Nombre de la pista',
    'drive.defaultName': 'Mi pista',
    'drive.trackLook': 'Paisaje',
    'drive.tryTrack': 'Guardar y conducir',
    'drive.saveTrack': 'Guardar',
    'drive.trackSaved': '¡Guardada!',
    'drive.export': 'Exportar',
    'drive.copyCode': 'Copiar código',
    'drive.copied': '¡Código de la pista copiado! Pégalo donde quieras para compartirla.',
    'drive.import': 'Importar',
    'drive.importHelp': 'Pega un código de pista o elige un archivo de pista.',
    'drive.importCode': 'Código de pista',
    'drive.loadCode': 'Cargar',
    'drive.chooseFile': 'Elegir archivo',
    'drive.importFailed': 'Eso no es una pista de Playbox.',
    'drive.imported': '¡Pista cargada! Guárdala para conservarla.',
    'drive.deleteTrack': 'Eliminar',
    'drive.deleteConfirm': 'Toca otra vez para eliminar',
    'drive.track.empty': 'Añade piezas de carretera. La carretera discontinua une sola el final con la salida.',
    'drive.track.short': 'Un poco corta: añade más carretera.',
    'drive.track.tight': 'La vuelta a la salida es demasiado cerrada (círculo rojo). Añade curvas hacia la salida.',
    'drive.track.crossing': 'La carretera choca consigo misma (círculo rojo). Prueba otra curva.',
    'drive.track.ok': '¡Lista para conducir! Mide {length}.',
    'drive.paintColor': 'Color {number}',
    'drive.customize': 'Personalizar',
    'drive.presets': 'Estilos de carreras callejeras',
    'drive.preset.muscle': 'Músculo de medianoche',
    'drive.preset.silverGt': 'GT plateado',
    'drive.preset.limeTuner': 'Tuner lima',
    'drive.preset.orangeRocket': 'Cohete naranja',
    'drive.preset.neonPink': 'Rosa neón',
    'drive.custom.decal': 'Gráficos laterales',
    'drive.decal.none': 'Ninguno',
    'drive.decal.swirl': 'Ondas',
    'drive.decal.tribal': 'Tribal',
    'drive.decal.flames': 'Llamas',
    'drive.custom.decalColor': 'Color de gráficos',
    'drive.custom.hood': 'Capó',
    'drive.hood.none': 'Liso',
    'drive.hood.scoop': 'Toma de aire',
    'drive.hood.blower': 'Compresor',
    'drive.custom.finish': 'Pintura',
    'drive.finish.gloss': 'Brillante',
    'drive.finish.matte': 'Mate',
    'drive.finish.chrome': 'Cromada',
    'drive.custom.stripes': 'Franjas',
    'drive.stripes.none': 'Ninguna',
    'drive.stripes.single': 'Una',
    'drive.stripes.double': 'Dos',
    'drive.custom.stripeColor': 'Color de franjas',
    'drive.custom.rims': 'Llantas',
    'drive.rims.silver': 'Plata',
    'drive.rims.black': 'Negras',
    'drive.rims.gold': 'Oro',
    'drive.rims.red': 'Rojas',
    'drive.custom.wing': 'Alerón',
    'drive.wing.auto': 'De serie',
    'drive.wing.none': 'Ninguno',
    'drive.wing.small': 'Pequeño',
    'drive.wing.big': 'Grande',
    'drive.custom.glow': 'Luces de bajo',
    'drive.glow.auto': 'De noche',
    'drive.glow.off': 'Apagadas',
    'drive.colorChoice': 'Color {number}',
    'drive.steering': 'Dirección',
    'drive.control.buttons': 'Botones',
    'drive.control.tilt': 'Inclinar el teléfono',
    'drive.tiltNote': 'Sujeta el teléfono como un volante e inclínalo para girar.',
    'drive.tiltDenied': 'No se permitió el acceso al movimiento, así que vuelven los botones. Puedes permitirlo en los ajustes del navegador.',
    'drive.tiltHint': '¡Inclina para girar! Toca la pantalla para enderezar.',
    'drive.level': 'Nivel',
    'drive.difficulty.easy': 'Fácil',
    'drive.difficulty.medium': 'Medio',
    'drive.difficulty.hard': 'Difícil',
    'drive.difficultyBlurb.easy': 'Puntos en el centro de la carretera',
    'drive.difficultyBlurb.medium': 'Puntos de un lado a otro',
    'drive.difficultyBlurb.hard': 'Puntos en los bordes y en las curvas',
    'drive.go': '¡A conducir!',
    'drive.best': 'Récord: {time}',
    'drive.noBest': 'Aún no hay récord',
    'drive.points': 'Puntos',
    'drive.time': 'Tiempo',
    'drive.lap': 'Vuelta {lap}',
    'drive.left': 'Girar a la izquierda',
    'drive.right': 'Girar a la derecha',
    'drive.pause': 'Pausa',
    'drive.paused': 'En pausa',
    'drive.resume': 'Seguir conduciendo',
    'drive.restart': 'Empezar de nuevo',
    'drive.change': 'Cambiar coche o pista',
    'drive.countGo': '¡YA!',
    'drive.collectAll': '¡Recoge todos los puntos!',
    'drive.wrongWay': '¡Sentido contrario! Da la vuelta',
    'drive.finishTitle': '¡Todos los puntos recogidos!',
    'drive.finishTime': 'Tiempo: {time}',
    'drive.newBest': '¡Nuevo récord!',
    'drive.again': 'Conducir otra vez',
    'drive.keys': 'Flechas o A y D para girar · Pasa por las flechas azules para un turbo',
    'drive.pointsLeft': { one: 'Queda {count} punto', other: 'Quedan {count} puntos' },
  },
  'pt-BR': {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Visão de direção',
    'drive.loading': 'Construindo a pista…',
    'drive.where': 'Para onde vamos?',
    'drive.scenario.city': 'Cidade neon',
    'drive.scenario.jungle': 'Selva',
    'drive.scenario.wasteland': 'Terra devastada',
    'drive.scenarioBlurb.city': 'Moedas de ouro sob luzes de neon',
    'drive.scenarioBlurb.jungle': 'Esmeraldas entre templos antigos',
    'drive.scenarioBlurb.wasteland': 'Engrenagens na neve e depois no deserto',
    'drive.car': 'Seu carro',
    'drive.car.comet': 'Cometa',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Pintura',
    'drive.music': 'Música',
    'drive.musicOn': 'Música ligada. Desligar a música',
    'drive.musicOff': 'Música desligada. Ligar a música',
    'drive.myTracks': 'Minhas pistas',
    'drive.buildTrack': '+ Montar uma pista',
    'drive.editTrack': 'Editar esta pista',
    'drive.builder': 'Montador de pistas',
    'drive.closeBuilder': 'Fechar o montador de pistas',
    'drive.trackMap': 'Sua pista vista de cima',
    'drive.pieces': 'Peças de estrada',
    'drive.straight': 'Reta',
    'drive.curveLeft': 'Curva à esquerda',
    'drive.curveRight': 'Curva à direita',
    'drive.undo': 'Desfazer',
    'drive.clearTrack': 'Limpar',
    'drive.trackName': 'Nome da pista',
    'drive.defaultName': 'Minha pista',
    'drive.trackLook': 'Paisagem',
    'drive.tryTrack': 'Salvar e dirigir',
    'drive.saveTrack': 'Salvar',
    'drive.trackSaved': 'Salva!',
    'drive.export': 'Exportar',
    'drive.copyCode': 'Copiar código',
    'drive.copied': 'Código da pista copiado! Cole onde quiser para compartilhar.',
    'drive.import': 'Importar',
    'drive.importHelp': 'Cole um código de pista ou escolha um arquivo de pista.',
    'drive.importCode': 'Código da pista',
    'drive.loadCode': 'Carregar',
    'drive.chooseFile': 'Escolher arquivo',
    'drive.importFailed': 'Isso não é uma pista do Playbox.',
    'drive.imported': 'Pista carregada! Salve para guardar.',
    'drive.deleteTrack': 'Apagar',
    'drive.deleteConfirm': 'Toque de novo para apagar',
    'drive.track.empty': 'Adicione peças de estrada. A estrada tracejada liga sozinha o fim ao começo.',
    'drive.track.short': 'Um pouco curta: adicione mais estrada.',
    'drive.track.tight': 'A volta até a largada está apertada demais (círculo vermelho). Adicione curvas em direção à largada.',
    'drive.track.crossing': 'A estrada bate nela mesma (círculo vermelho). Tente outra curva.',
    'drive.track.ok': 'Pronta para dirigir! Tem {length}.',
    'drive.paintColor': 'Cor {number}',
    'drive.customize': 'Personalizar',
    'drive.presets': 'Estilos de racha',
    'drive.preset.muscle': 'Músculo da meia-noite',
    'drive.preset.silverGt': 'GT prateado',
    'drive.preset.limeTuner': 'Tuner limão',
    'drive.preset.orangeRocket': 'Foguete laranja',
    'drive.preset.neonPink': 'Rosa neon',
    'drive.custom.decal': 'Adesivos laterais',
    'drive.decal.none': 'Nenhum',
    'drive.decal.swirl': 'Ondas',
    'drive.decal.tribal': 'Tribal',
    'drive.decal.flames': 'Chamas',
    'drive.custom.decalColor': 'Cor dos adesivos',
    'drive.custom.hood': 'Capô',
    'drive.hood.none': 'Liso',
    'drive.hood.scoop': 'Entrada de ar',
    'drive.hood.blower': 'Compressor',
    'drive.custom.finish': 'Pintura',
    'drive.finish.gloss': 'Brilhante',
    'drive.finish.matte': 'Fosca',
    'drive.finish.chrome': 'Cromada',
    'drive.custom.stripes': 'Faixas',
    'drive.stripes.none': 'Nenhuma',
    'drive.stripes.single': 'Uma',
    'drive.stripes.double': 'Duas',
    'drive.custom.stripeColor': 'Cor das faixas',
    'drive.custom.rims': 'Rodas',
    'drive.rims.silver': 'Prata',
    'drive.rims.black': 'Pretas',
    'drive.rims.gold': 'Douradas',
    'drive.rims.red': 'Vermelhas',
    'drive.custom.wing': 'Aerofólio',
    'drive.wing.auto': 'De fábrica',
    'drive.wing.none': 'Nenhum',
    'drive.wing.small': 'Pequeno',
    'drive.wing.big': 'Grande',
    'drive.custom.glow': 'Luz de baixo',
    'drive.glow.auto': 'À noite',
    'drive.glow.off': 'Desligada',
    'drive.colorChoice': 'Cor {number}',
    'drive.steering': 'Direção',
    'drive.control.buttons': 'Botões',
    'drive.control.tilt': 'Inclinar o celular',
    'drive.tiltNote': 'Segure o celular como um volante e incline para virar.',
    'drive.tiltDenied': 'O acesso ao movimento não foi permitido, então os botões voltaram. Você pode permitir nas configurações do navegador.',
    'drive.tiltHint': 'Incline para virar! Toque na tela para endireitar.',
    'drive.level': 'Nível',
    'drive.difficulty.easy': 'Fácil',
    'drive.difficulty.medium': 'Médio',
    'drive.difficulty.hard': 'Difícil',
    'drive.difficultyBlurb.easy': 'Pontos no meio da pista',
    'drive.difficultyBlurb.medium': 'Pontos de um lado para o outro',
    'drive.difficultyBlurb.hard': 'Pontos nas beiradas e nas curvas',
    'drive.go': 'Acelerar!',
    'drive.best': 'Recorde: {time}',
    'drive.noBest': 'Ainda sem recorde',
    'drive.points': 'Pontos',
    'drive.time': 'Tempo',
    'drive.lap': 'Volta {lap}',
    'drive.left': 'Virar à esquerda',
    'drive.right': 'Virar à direita',
    'drive.pause': 'Pausar',
    'drive.paused': 'Pausado',
    'drive.resume': 'Continuar dirigindo',
    'drive.restart': 'Começar de novo',
    'drive.change': 'Trocar carro ou pista',
    'drive.countGo': 'JÁ!',
    'drive.collectAll': 'Pegue todos os pontos!',
    'drive.wrongWay': 'Contramão! Dê a volta',
    'drive.finishTitle': 'Todos os pontos coletados!',
    'drive.finishTime': 'Tempo: {time}',
    'drive.newBest': 'Novo recorde!',
    'drive.again': 'Dirigir de novo',
    'drive.keys': 'Setas ou A e D para virar · Passe pelas setas azuis para um turbo',
    'drive.pointsLeft': { one: 'Falta {count} ponto', other: 'Faltam {count} pontos' },
  },
  de: {
    'drive.pageTitle': 'Turbo Drive · Playbox',
    'drive.area': 'Fahransicht',
    'drive.loading': 'Die Strecke wird gebaut…',
    'drive.where': 'Wohin geht’s?',
    'drive.scenario.city': 'Neonstadt',
    'drive.scenario.jungle': 'Dschungel',
    'drive.scenario.wasteland': 'Ödland',
    'drive.scenarioBlurb.city': 'Goldmünzen unter Neonlichtern',
    'drive.scenarioBlurb.jungle': 'Smaragde zwischen alten Tempeln',
    'drive.scenarioBlurb.wasteland': 'Zahnräder im Schnee, dann in der Wüste',
    'drive.car': 'Dein Auto',
    'drive.car.comet': 'Komet',
    'drive.car.racer': 'Racer',
    'drive.car.rover': 'Rover',
    'drive.paint': 'Lack',
    'drive.music': 'Musik',
    'drive.musicOn': 'Musik ist an. Musik ausschalten',
    'drive.musicOff': 'Musik ist aus. Musik einschalten',
    'drive.myTracks': 'Meine Strecken',
    'drive.buildTrack': '+ Strecke bauen',
    'drive.editTrack': 'Diese Strecke bearbeiten',
    'drive.builder': 'Streckenbauer',
    'drive.closeBuilder': 'Streckenbauer schließen',
    'drive.trackMap': 'Deine Strecke von oben',
    'drive.pieces': 'Straßenteile',
    'drive.straight': 'Gerade',
    'drive.curveLeft': 'Linkskurve',
    'drive.curveRight': 'Rechtskurve',
    'drive.undo': 'Rückgängig',
    'drive.clearTrack': 'Löschen',
    'drive.trackName': 'Name der Strecke',
    'drive.defaultName': 'Meine Strecke',
    'drive.trackLook': 'Landschaft',
    'drive.tryTrack': 'Speichern und fahren',
    'drive.saveTrack': 'Speichern',
    'drive.trackSaved': 'Gespeichert!',
    'drive.export': 'Exportieren',
    'drive.copyCode': 'Code kopieren',
    'drive.copied': 'Streckencode kopiert! Füg ihn irgendwo ein, um die Strecke zu teilen.',
    'drive.import': 'Importieren',
    'drive.importHelp': 'Füg einen Streckencode ein oder wähle eine Streckendatei.',
    'drive.importCode': 'Streckencode',
    'drive.loadCode': 'Laden',
    'drive.chooseFile': 'Datei wählen',
    'drive.importFailed': 'Das ist keine Playbox-Strecke.',
    'drive.imported': 'Strecke geladen! Speichere sie, um sie zu behalten.',
    'drive.deleteTrack': 'Löschen',
    'drive.deleteConfirm': 'Nochmal tippen zum Löschen',
    'drive.track.empty': 'Füg Straßenteile hinzu. Die gestrichelte Straße führt das Ende von selbst zurück zum Start.',
    'drive.track.short': 'Etwas kurz: Füg mehr Straße hinzu.',
    'drive.track.tight': 'Der Weg zurück zum Start ist zu eng (roter Kreis). Füg mehr Kurven Richtung Start hinzu.',
    'drive.track.crossing': 'Die Straße stößt an sich selbst (roter Kreis). Versuch eine andere Kurve.',
    'drive.track.ok': 'Bereit zum Fahren! {length} lang.',
    'drive.paintColor': 'Farbe {number}',
    'drive.customize': 'Anpassen',
    'drive.presets': 'Straßenrenner-Looks',
    'drive.preset.muscle': 'Mitternachts-Muscle',
    'drive.preset.silverGt': 'Silberner GT',
    'drive.preset.limeTuner': 'Limetten-Tuner',
    'drive.preset.orangeRocket': 'Orange Rakete',
    'drive.preset.neonPink': 'Neonpink',
    'drive.custom.decal': 'Seitengrafik',
    'drive.decal.none': 'Keine',
    'drive.decal.swirl': 'Schwünge',
    'drive.decal.tribal': 'Tribal',
    'drive.decal.flames': 'Flammen',
    'drive.custom.decalColor': 'Grafikfarbe',
    'drive.custom.hood': 'Motorhaube',
    'drive.hood.none': 'Glatt',
    'drive.hood.scoop': 'Lufthutze',
    'drive.hood.blower': 'Kompressor',
    'drive.custom.finish': 'Lack',
    'drive.finish.gloss': 'Glänzend',
    'drive.finish.matte': 'Matt',
    'drive.finish.chrome': 'Chrom',
    'drive.custom.stripes': 'Streifen',
    'drive.stripes.none': 'Keine',
    'drive.stripes.single': 'Einer',
    'drive.stripes.double': 'Zwei',
    'drive.custom.stripeColor': 'Streifenfarbe',
    'drive.custom.rims': 'Felgen',
    'drive.rims.silver': 'Silber',
    'drive.rims.black': 'Schwarz',
    'drive.rims.gold': 'Gold',
    'drive.rims.red': 'Rot',
    'drive.custom.wing': 'Heckflügel',
    'drive.wing.auto': 'Serie',
    'drive.wing.none': 'Keiner',
    'drive.wing.small': 'Klein',
    'drive.wing.big': 'Groß',
    'drive.custom.glow': 'Unterbodenlicht',
    'drive.glow.auto': 'Nachts',
    'drive.glow.off': 'Aus',
    'drive.colorChoice': 'Farbe {number}',
    'drive.steering': 'Lenken',
    'drive.control.buttons': 'Tasten',
    'drive.control.tilt': 'Handy neigen',
    'drive.tiltNote': 'Halte das Handy wie ein Lenkrad und neige es zum Lenken.',
    'drive.tiltDenied': 'Der Zugriff auf Bewegung wurde nicht erlaubt, deshalb sind die Tasten zurück. Du kannst ihn in den Browser-Einstellungen erlauben.',
    'drive.tiltHint': 'Neigen zum Lenken! Tipp auf den Bildschirm zum Geradeausfahren.',
    'drive.level': 'Stufe',
    'drive.difficulty.easy': 'Leicht',
    'drive.difficulty.medium': 'Mittel',
    'drive.difficulty.hard': 'Schwer',
    'drive.difficultyBlurb.easy': 'Punkte mitten auf der Straße',
    'drive.difficultyBlurb.medium': 'Punkte mal links, mal rechts',
    'drive.difficultyBlurb.hard': 'Punkte am Rand und in den Kurven',
    'drive.go': 'Losfahren!',
    'drive.best': 'Bestzeit: {time}',
    'drive.noBest': 'Noch keine Bestzeit',
    'drive.points': 'Punkte',
    'drive.time': 'Zeit',
    'drive.lap': 'Runde {lap}',
    'drive.left': 'Nach links lenken',
    'drive.right': 'Nach rechts lenken',
    'drive.pause': 'Pause',
    'drive.paused': 'Pause',
    'drive.resume': 'Weiterfahren',
    'drive.restart': 'Neu starten',
    'drive.change': 'Auto oder Strecke wechseln',
    'drive.countGo': 'LOS!',
    'drive.collectAll': 'Sammle alle Punkte!',
    'drive.wrongWay': 'Falsche Richtung! Dreh um',
    'drive.finishTitle': 'Alle Punkte gesammelt!',
    'drive.finishTime': 'Zeit: {time}',
    'drive.newBest': 'Neue Bestzeit!',
    'drive.again': 'Nochmal fahren',
    'drive.keys': 'Pfeile oder A und D zum Lenken · Fahr über die blauen Pfeile für einen Turbo',
    'drive.pointsLeft': { one: 'Noch {count} Punkt', other: 'Noch {count} Punkte' },
  },
});
