// Molecules texts: the interface, atom names, and a name and fun fact for
// every molecule (keys match the ids in logic.js).

import { addStrings } from '../../shared/i18n.js';

addStrings({
  en: {
    'molecules.pageTitle': 'Molecules · Playbox',
    'molecules.mode': 'Mode',
    'molecules.easy': 'Easy',
    'molecules.hard': 'Hard',
    'molecules.levels': 'All molecules',
    'molecules.levelOf': 'Level {number} of {total}',
    'molecules.prev': 'Previous molecule',
    'molecules.next': 'Next molecule',
    'molecules.locked': 'Locked: build the one before first',
    'molecules.goal': 'Build',
    'molecules.madeOf': 'Made of',
    'molecules.mystery': 'What is it made of? Think, then build!',
    'molecules.hint': 'Hint',
    'molecules.atoms': 'Atoms',
    'molecules.area': 'Building area',
    'molecules.addAtom': 'Add {element}',
    'molecules.undo': 'Undo',
    'molecules.remove': 'Remove atom',
    'molecules.hands': { one: '{count} hand', other: '{count} hands' },
    'molecules.freeHands': { one: '{count} free hand', other: '{count} free hands' },
    'molecules.atomLabel': '{element}, {hands}',
    'molecules.start': 'Tap an atom below to start.',
    'molecules.tip': 'Tap an atom to pick it. Tap two atoms to join them; tap again for a double bond. Tap a bond to undo it.',
    'molecules.picked': '{element} is picked, with {hands}. Add an atom below, or tap another atom to join them.',
    'molecules.pickedFull': '{element} is picked. All its hands are holding.',
    'molecules.noHands': '{element} has no free hands.',
    'molecules.notYet': 'Every hand is holding, but this isn’t {name} yet. Look at the picture again!',
    'molecules.notYetHard': 'Every hand is holding, but this isn’t {name} yet. Need a hint?',
    'molecules.notYetCount': 'Every hand is holding, but this isn’t {name} yet. Check the atom list!',
    'molecules.winTitle': 'You built {name}!',
    'molecules.hardWin': 'Built without the picture. Amazing!',
    'molecules.nextLevel': 'Next molecule',
    'molecules.again': 'Build again',
    'molecules.allDone': 'You built every molecule!',
    'molecules.doneEasy': 'built',
    'molecules.doneHard': 'built in hard mode',
    'element.H': 'Hydrogen',
    'element.C': 'Carbon',
    'element.N': 'Nitrogen',
    'element.O': 'Oxygen',
    'element.Na': 'Sodium',
    'element.Cl': 'Chlorine',
    'molecule.hydrogen.name': 'Hydrogen gas',
    'molecule.hydrogen.fact': 'The lightest gas there is. The Sun is mostly hydrogen!',
    'molecule.oxygen.name': 'Oxygen gas',
    'molecule.oxygen.fact': 'You breathe it in all day long. Plants make it from sunlight.',
    'molecule.nitrogen.name': 'Nitrogen gas',
    'molecule.nitrogen.fact': 'Almost four out of five bits of air are nitrogen.',
    'molecule.salt.name': 'Table salt',
    'molecule.salt.fact': 'Sodium and chlorine together make the salt you sprinkle on food.',
    'molecule.water.name': 'Water',
    'molecule.water.fact': 'Two hydrogens and one oxygen. More than half of your body is water!',
    'molecule.carbonDioxide.name': 'Carbon dioxide',
    'molecule.carbonDioxide.fact': 'You breathe it out and plants breathe it in. It puts the fizz in soda!',
    'molecule.ammonia.name': 'Ammonia',
    'molecule.ammonia.fact': 'It has a very strong smell. Farmers use it to help plants grow.',
    'molecule.hydrogenPeroxide.name': 'Hydrogen peroxide',
    'molecule.hydrogenPeroxide.fact': 'Like water with one extra oxygen. It fizzes when it cleans a scrape.',
    'molecule.acetylene.name': 'Acetylene',
    'molecule.acetylene.fact': 'Its flame is so hot that welders use it to cut and join metal.',
    'molecule.methane.name': 'Methane',
    'molecule.methane.fact': 'The gas in many kitchen stoves. Cows burp it out, too!',
    'molecule.ethylene.name': 'Ethylene',
    'molecule.ethylene.fact': 'Fruits give it off as they ripen. A banana helps the fruit next to it ripen faster!',
    'molecule.urea.name': 'Urea',
    'molecule.urea.fact': 'Your body makes it to get rid of extra nitrogen. It’s in pee!',
    'molecule.aceticAcid.name': 'Acetic acid',
    'molecule.aceticAcid.fact': 'It gives vinegar its sour taste and sharp smell.',
    'molecule.glycine.name': 'Glycine',
    'molecule.glycine.fact': 'The smallest of the building blocks that make up the proteins in your body.',
    'molecule.propane.name': 'Propane',
    'molecule.propane.fact': 'The gas in barbecue tanks. It’s squeezed so tight it turns into a liquid.',
    'molecule.benzene.name': 'Benzene',
    'molecule.benzene.fact': 'Six carbons hold hands in a ring. A scientist once dreamed of a snake biting its tail and guessed its shape!',
  },
  it: {
    'molecules.pageTitle': 'Molecole · Playbox',
    'molecules.mode': 'Modalità',
    'molecules.easy': 'Facile',
    'molecules.hard': 'Difficile',
    'molecules.levels': 'Tutte le molecole',
    'molecules.levelOf': 'Livello {number} di {total}',
    'molecules.prev': 'Molecola precedente',
    'molecules.next': 'Molecola successiva',
    'molecules.locked': 'Bloccata: prima costruisci quella prima',
    'molecules.goal': 'Costruisci',
    'molecules.madeOf': 'Fatta di',
    'molecules.mystery': 'Di cosa è fatta? Pensaci, poi costruiscila!',
    'molecules.hint': 'Aiuto',
    'molecules.atoms': 'Atomi',
    'molecules.area': 'Area di costruzione',
    'molecules.addAtom': 'Aggiungi {element}',
    'molecules.undo': 'Annulla',
    'molecules.remove': 'Togli atomo',
    'molecules.hands': { one: '{count} mano', other: '{count} mani' },
    'molecules.freeHands': { one: '{count} mano libera', other: '{count} mani libere' },
    'molecules.atomLabel': '{element}, {hands}',
    'molecules.start': 'Tocca un atomo qui sotto per iniziare.',
    'molecules.tip': 'Tocca un atomo per sceglierlo. Tocca due atomi per unirli; tocca ancora per un legame doppio. Tocca un legame per toglierlo.',
    'molecules.picked': 'Hai scelto {element}, con {hands}. Aggiungi un atomo qui sotto, o tocca un altro atomo per unirli.',
    'molecules.pickedFull': 'Hai scelto {element}. Tutte le sue mani sono occupate.',
    'molecules.noHands': '{element} non ha mani libere.',
    'molecules.notYet': 'Tutte le mani sono occupate, ma questa non è ancora {name}. Guarda di nuovo il disegno!',
    'molecules.notYetHard': 'Tutte le mani sono occupate, ma questa non è ancora {name}. Vuoi un aiuto?',
    'molecules.notYetCount': 'Tutte le mani sono occupate, ma questa non è ancora {name}. Controlla l’elenco degli atomi!',
    'molecules.winTitle': 'Hai costruito {name}!',
    'molecules.hardWin': 'Costruita senza disegno. Fantastico!',
    'molecules.nextLevel': 'Prossima molecola',
    'molecules.again': 'Costruisci di nuovo',
    'molecules.allDone': 'Hai costruito tutte le molecole!',
    'molecules.doneEasy': 'costruita',
    'molecules.doneHard': 'costruita in modalità difficile',
    'element.H': 'Idrogeno',
    'element.C': 'Carbonio',
    'element.N': 'Azoto',
    'element.O': 'Ossigeno',
    'element.Na': 'Sodio',
    'element.Cl': 'Cloro',
    'molecule.hydrogen.name': 'Idrogeno gassoso',
    'molecule.hydrogen.fact': 'Il gas più leggero che esista. Il Sole è fatto soprattutto di idrogeno!',
    'molecule.oxygen.name': 'Ossigeno gassoso',
    'molecule.oxygen.fact': 'Lo respiri tutto il giorno. Le piante lo producono con la luce del sole.',
    'molecule.nitrogen.name': 'Azoto gassoso',
    'molecule.nitrogen.fact': 'Quasi quattro pezzetti d’aria su cinque sono azoto.',
    'molecule.salt.name': 'Sale da cucina',
    'molecule.salt.fact': 'Sodio e cloro insieme formano il sale che metti sul cibo.',
    'molecule.water.name': 'Acqua',
    'molecule.water.fact': 'Due idrogeni e un ossigeno. Più di metà del tuo corpo è acqua!',
    'molecule.carbonDioxide.name': 'Anidride carbonica',
    'molecule.carbonDioxide.fact': 'Tu la espiri e le piante la respirano. Fa le bollicine nelle bibite!',
    'molecule.ammonia.name': 'Ammoniaca',
    'molecule.ammonia.fact': 'Ha un odore fortissimo. Gli agricoltori la usano per far crescere le piante.',
    'molecule.hydrogenPeroxide.name': 'Acqua ossigenata',
    'molecule.hydrogenPeroxide.fact': 'Come l’acqua, con un ossigeno in più. Fa le bollicine quando pulisce un graffio.',
    'molecule.acetylene.name': 'Acetilene',
    'molecule.acetylene.fact': 'La sua fiamma è così calda che i saldatori la usano per tagliare e unire il metallo.',
    'molecule.methane.name': 'Metano',
    'molecule.methane.fact': 'Il gas di tanti fornelli di cucina. Anche le mucche lo fanno uscire con i rutti!',
    'molecule.ethylene.name': 'Etilene',
    'molecule.ethylene.fact': 'La frutta lo libera mentre matura. Una banana fa maturare prima la frutta vicina!',
    'molecule.urea.name': 'Urea',
    'molecule.urea.fact': 'Il tuo corpo la produce per liberarsi dell’azoto in più. È nella pipì!',
    'molecule.aceticAcid.name': 'Acido acetico',
    'molecule.aceticAcid.fact': 'Dà all’aceto il suo sapore aspro e il suo odore pungente.',
    'molecule.glycine.name': 'Glicina',
    'molecule.glycine.fact': 'Il più piccolo dei mattoncini che formano le proteine del tuo corpo.',
    'molecule.propane.name': 'Propano',
    'molecule.propane.fact': 'Il gas delle bombole per il barbecue. È così compresso che diventa liquido.',
    'molecule.benzene.name': 'Benzene',
    'molecule.benzene.fact': 'Sei carboni si tengono per mano in un anello. Uno scienziato sognò un serpente che si mordeva la coda e ne indovinò la forma!',
  },
  es: {
    'molecules.pageTitle': 'Moléculas · Playbox',
    'molecules.mode': 'Modo',
    'molecules.easy': 'Fácil',
    'molecules.hard': 'Difícil',
    'molecules.levels': 'Todas las moléculas',
    'molecules.levelOf': 'Nivel {number} de {total}',
    'molecules.prev': 'Molécula anterior',
    'molecules.next': 'Molécula siguiente',
    'molecules.locked': 'Bloqueada: primero construye la anterior',
    'molecules.goal': 'Construye',
    'molecules.madeOf': 'Hecha de',
    'molecules.mystery': '¿De qué está hecha? ¡Piénsalo y luego constrúyela!',
    'molecules.hint': 'Pista',
    'molecules.atoms': 'Átomos',
    'molecules.area': 'Zona de construcción',
    'molecules.addAtom': 'Añadir {element}',
    'molecules.undo': 'Deshacer',
    'molecules.remove': 'Quitar átomo',
    'molecules.hands': { one: '{count} mano', other: '{count} manos' },
    'molecules.freeHands': { one: '{count} mano libre', other: '{count} manos libres' },
    'molecules.atomLabel': '{element}, {hands}',
    'molecules.start': 'Toca un átomo de abajo para empezar.',
    'molecules.tip': 'Toca un átomo para elegirlo. Toca dos átomos para unirlos; toca otra vez para un enlace doble. Toca un enlace para quitarlo.',
    'molecules.picked': 'Has elegido {element}, con {hands}. Añade un átomo de abajo o toca otro átomo para unirlos.',
    'molecules.pickedFull': 'Has elegido {element}. Todas sus manos están ocupadas.',
    'molecules.noHands': '{element} no tiene manos libres.',
    'molecules.notYet': 'Todas las manos están ocupadas, pero esto aún no es {name}. ¡Mira otra vez el dibujo!',
    'molecules.notYetHard': 'Todas las manos están ocupadas, pero esto aún no es {name}. ¿Quieres una pista?',
    'molecules.notYetCount': 'Todas las manos están ocupadas, pero esto aún no es {name}. ¡Revisa la lista de átomos!',
    'molecules.winTitle': '¡Has construido {name}!',
    'molecules.hardWin': 'Construida sin el dibujo. ¡Increíble!',
    'molecules.nextLevel': 'Siguiente molécula',
    'molecules.again': 'Construir otra vez',
    'molecules.allDone': '¡Has construido todas las moléculas!',
    'molecules.doneEasy': 'construida',
    'molecules.doneHard': 'construida en modo difícil',
    'element.H': 'Hidrógeno',
    'element.C': 'Carbono',
    'element.N': 'Nitrógeno',
    'element.O': 'Oxígeno',
    'element.Na': 'Sodio',
    'element.Cl': 'Cloro',
    'molecule.hydrogen.name': 'Gas hidrógeno',
    'molecule.hydrogen.fact': 'El gas más ligero que existe. ¡El Sol es casi todo hidrógeno!',
    'molecule.oxygen.name': 'Gas oxígeno',
    'molecule.oxygen.fact': 'Lo respiras todo el día. Las plantas lo fabrican con la luz del sol.',
    'molecule.nitrogen.name': 'Gas nitrógeno',
    'molecule.nitrogen.fact': 'Casi cuatro de cada cinco trocitos de aire son nitrógeno.',
    'molecule.salt.name': 'Sal de mesa',
    'molecule.salt.fact': 'El sodio y el cloro juntos forman la sal que le pones a la comida.',
    'molecule.water.name': 'Agua',
    'molecule.water.fact': 'Dos hidrógenos y un oxígeno. ¡Más de la mitad de tu cuerpo es agua!',
    'molecule.carbonDioxide.name': 'Dióxido de carbono',
    'molecule.carbonDioxide.fact': 'Tú lo echas al respirar y las plantas lo toman. ¡Hace las burbujas de los refrescos!',
    'molecule.ammonia.name': 'Amoníaco',
    'molecule.ammonia.fact': 'Huele muy fuerte. Los agricultores lo usan para que las plantas crezcan.',
    'molecule.hydrogenPeroxide.name': 'Agua oxigenada',
    'molecule.hydrogenPeroxide.fact': 'Como el agua, pero con un oxígeno más. Hace burbujas al limpiar un rasguño.',
    'molecule.acetylene.name': 'Acetileno',
    'molecule.acetylene.fact': 'Su llama es tan caliente que los soldadores la usan para cortar y unir metal.',
    'molecule.methane.name': 'Metano',
    'molecule.methane.fact': 'El gas de muchas cocinas. ¡Las vacas también lo sueltan al eructar!',
    'molecule.ethylene.name': 'Etileno',
    'molecule.ethylene.fact': 'La fruta lo suelta al madurar. ¡Un plátano hace que la fruta de al lado madure antes!',
    'molecule.urea.name': 'Urea',
    'molecule.urea.fact': 'Tu cuerpo la fabrica para librarse del nitrógeno que sobra. ¡Está en el pis!',
    'molecule.aceticAcid.name': 'Ácido acético',
    'molecule.aceticAcid.fact': 'Le da al vinagre su sabor ácido y su olor fuerte.',
    'molecule.glycine.name': 'Glicina',
    'molecule.glycine.fact': 'La más pequeña de las piezas que forman las proteínas de tu cuerpo.',
    'molecule.propane.name': 'Propano',
    'molecule.propane.fact': 'El gas de las bombonas de barbacoa. Está tan apretado que se vuelve líquido.',
    'molecule.benzene.name': 'Benceno',
    'molecule.benzene.fact': 'Seis carbonos se dan la mano en un anillo. ¡Un científico soñó con una serpiente que se mordía la cola y adivinó su forma!',
  },
  'pt-BR': {
    'molecules.pageTitle': 'Moléculas · Playbox',
    'molecules.mode': 'Modo',
    'molecules.easy': 'Fácil',
    'molecules.hard': 'Difícil',
    'molecules.levels': 'Todas as moléculas',
    'molecules.levelOf': 'Nível {number} de {total}',
    'molecules.prev': 'Molécula anterior',
    'molecules.next': 'Próxima molécula',
    'molecules.locked': 'Bloqueada: monte a anterior primeiro',
    'molecules.goal': 'Monte',
    'molecules.madeOf': 'Feita de',
    'molecules.mystery': 'Do que ela é feita? Pense e depois monte!',
    'molecules.hint': 'Dica',
    'molecules.atoms': 'Átomos',
    'molecules.area': 'Área de montagem',
    'molecules.addAtom': 'Adicionar {element}',
    'molecules.undo': 'Desfazer',
    'molecules.remove': 'Tirar átomo',
    'molecules.hands': { one: '{count} mão', other: '{count} mãos' },
    'molecules.freeHands': { one: '{count} mão livre', other: '{count} mãos livres' },
    'molecules.atomLabel': '{element}, {hands}',
    'molecules.start': 'Toque em um átomo lá embaixo para começar.',
    'molecules.tip': 'Toque em um átomo para escolhê-lo. Toque em dois átomos para ligá-los; toque de novo para uma ligação dupla. Toque em uma ligação para desfazê-la.',
    'molecules.picked': 'Você escolheu {element}, com {hands}. Adicione um átomo lá embaixo ou toque em outro átomo para ligá-los.',
    'molecules.pickedFull': 'Você escolheu {element}. Todas as mãos dele estão ocupadas.',
    'molecules.noHands': '{element} não tem mãos livres.',
    'molecules.notYet': 'Todas as mãos estão ocupadas, mas isto ainda não é {name}. Olhe o desenho de novo!',
    'molecules.notYetHard': 'Todas as mãos estão ocupadas, mas isto ainda não é {name}. Quer uma dica?',
    'molecules.notYetCount': 'Todas as mãos estão ocupadas, mas isto ainda não é {name}. Confira a lista de átomos!',
    'molecules.winTitle': 'Você montou {name}!',
    'molecules.hardWin': 'Montada sem o desenho. Incrível!',
    'molecules.nextLevel': 'Próxima molécula',
    'molecules.again': 'Montar de novo',
    'molecules.allDone': 'Você montou todas as moléculas!',
    'molecules.doneEasy': 'montada',
    'molecules.doneHard': 'montada no modo difícil',
    'element.H': 'Hidrogênio',
    'element.C': 'Carbono',
    'element.N': 'Nitrogênio',
    'element.O': 'Oxigênio',
    'element.Na': 'Sódio',
    'element.Cl': 'Cloro',
    'molecule.hydrogen.name': 'Gás hidrogênio',
    'molecule.hydrogen.fact': 'O gás mais leve que existe. O Sol é quase todo hidrogênio!',
    'molecule.oxygen.name': 'Gás oxigênio',
    'molecule.oxygen.fact': 'Você respira oxigênio o dia todo. As plantas o fabricam com a luz do sol.',
    'molecule.nitrogen.name': 'Gás nitrogênio',
    'molecule.nitrogen.fact': 'Quase quatro de cada cinco pedacinhos do ar são nitrogênio.',
    'molecule.salt.name': 'Sal de cozinha',
    'molecule.salt.fact': 'Sódio e cloro juntos formam o sal que você põe na comida.',
    'molecule.water.name': 'Água',
    'molecule.water.fact': 'Dois hidrogênios e um oxigênio. Mais da metade do seu corpo é água!',
    'molecule.carbonDioxide.name': 'Dióxido de carbono',
    'molecule.carbonDioxide.fact': 'Você solta esse gás ao respirar e as plantas o absorvem. Ele faz as bolhas do refrigerante!',
    'molecule.ammonia.name': 'Amônia',
    'molecule.ammonia.fact': 'Tem um cheiro fortíssimo. Os agricultores usam amônia para as plantas crescerem.',
    'molecule.hydrogenPeroxide.name': 'Água oxigenada',
    'molecule.hydrogenPeroxide.fact': 'Como a água, mas com um oxigênio a mais. Faz espuma quando limpa um arranhão.',
    'molecule.acetylene.name': 'Acetileno',
    'molecule.acetylene.fact': 'A chama dele é tão quente que os soldadores a usam para cortar e unir metal.',
    'molecule.methane.name': 'Metano',
    'molecule.methane.fact': 'O gás de muitos fogões. As vacas também soltam metano quando arrotam!',
    'molecule.ethylene.name': 'Etileno',
    'molecule.ethylene.fact': 'As frutas soltam esse gás quando amadurecem. Uma banana faz a fruta do lado amadurecer mais rápido!',
    'molecule.urea.name': 'Ureia',
    'molecule.urea.fact': 'Seu corpo fabrica ureia para se livrar do nitrogênio que sobra. Ela está no xixi!',
    'molecule.aceticAcid.name': 'Ácido acético',
    'molecule.aceticAcid.fact': 'Dá ao vinagre o gosto azedo e o cheiro forte.',
    'molecule.glycine.name': 'Glicina',
    'molecule.glycine.fact': 'A menor das pecinhas que formam as proteínas do seu corpo.',
    'molecule.propane.name': 'Propano',
    'molecule.propane.fact': 'O gás dos botijões de churrasqueira. É tão apertado que vira líquido.',
    'molecule.benzene.name': 'Benzeno',
    'molecule.benzene.fact': 'Seis carbonos dão as mãos em um anel. Um cientista sonhou com uma cobra mordendo o próprio rabo e adivinhou a forma dele!',
  },
  de: {
    'molecules.pageTitle': 'Moleküle · Playbox',
    'molecules.mode': 'Modus',
    'molecules.easy': 'Leicht',
    'molecules.hard': 'Schwer',
    'molecules.levels': 'Alle Moleküle',
    'molecules.levelOf': 'Level {number} von {total}',
    'molecules.prev': 'Voriges Molekül',
    'molecules.next': 'Nächstes Molekül',
    'molecules.locked': 'Gesperrt: Bau zuerst das davor',
    'molecules.goal': 'Bau',
    'molecules.madeOf': 'Besteht aus',
    'molecules.mystery': 'Woraus besteht es? Überleg kurz, dann bau es!',
    'molecules.hint': 'Tipp',
    'molecules.atoms': 'Atome',
    'molecules.area': 'Baufläche',
    'molecules.addAtom': '{element} hinzufügen',
    'molecules.undo': 'Rückgängig',
    'molecules.remove': 'Atom entfernen',
    'molecules.hands': { one: '{count} Hand', other: '{count} Hände' },
    'molecules.freeHands': { one: '{count} freie Hand', other: '{count} freie Hände' },
    'molecules.atomLabel': '{element}, {hands}',
    'molecules.start': 'Tippe unten auf ein Atom, um anzufangen.',
    'molecules.tip': 'Tippe auf ein Atom, um es auszuwählen. Tippe auf zwei Atome, um sie zu verbinden; nochmal tippen für eine Doppelbindung. Tippe auf eine Bindung, um sie zu lösen.',
    'molecules.picked': '{element} ist ausgewählt, mit {hands}. Füg unten ein Atom hinzu oder tippe auf ein anderes Atom, um sie zu verbinden.',
    'molecules.pickedFull': '{element} ist ausgewählt. Alle seine Hände halten schon fest.',
    'molecules.noHands': '{element} hat keine freie Hand.',
    'molecules.notYet': 'Alle Hände halten fest, aber das ist noch nicht {name}. Schau dir das Bild nochmal an!',
    'molecules.notYetHard': 'Alle Hände halten fest, aber das ist noch nicht {name}. Brauchst du einen Tipp?',
    'molecules.notYetCount': 'Alle Hände halten fest, aber das ist noch nicht {name}. Schau dir die Atomliste an!',
    'molecules.winTitle': 'Du hast {name} gebaut!',
    'molecules.hardWin': 'Ganz ohne Bild gebaut. Super!',
    'molecules.nextLevel': 'Nächstes Molekül',
    'molecules.again': 'Nochmal bauen',
    'molecules.allDone': 'Du hast alle Moleküle gebaut!',
    'molecules.doneEasy': 'gebaut',
    'molecules.doneHard': 'im schweren Modus gebaut',
    'element.H': 'Wasserstoff',
    'element.C': 'Kohlenstoff',
    'element.N': 'Stickstoff',
    'element.O': 'Sauerstoff',
    'element.Na': 'Natrium',
    'element.Cl': 'Chlor',
    'molecule.hydrogen.name': 'Wasserstoffgas',
    'molecule.hydrogen.fact': 'Das leichteste Gas, das es gibt. Die Sonne besteht fast nur aus Wasserstoff!',
    'molecule.oxygen.name': 'Sauerstoffgas',
    'molecule.oxygen.fact': 'Du atmest ihn den ganzen Tag ein. Pflanzen machen ihn aus Sonnenlicht.',
    'molecule.nitrogen.name': 'Stickstoffgas',
    'molecule.nitrogen.fact': 'Fast vier von fünf Teilchen in der Luft sind Stickstoff.',
    'molecule.salt.name': 'Kochsalz',
    'molecule.salt.fact': 'Natrium und Chlor zusammen sind das Salz, das du aufs Essen streust.',
    'molecule.water.name': 'Wasser',
    'molecule.water.fact': 'Zwei Wasserstoffe und ein Sauerstoff. Mehr als die Hälfte deines Körpers ist Wasser!',
    'molecule.carbonDioxide.name': 'Kohlendioxid',
    'molecule.carbonDioxide.fact': 'Du atmest es aus, Pflanzen atmen es ein. Es macht die Bläschen in der Limo!',
    'molecule.ammonia.name': 'Ammoniak',
    'molecule.ammonia.fact': 'Es riecht sehr stark. Bauern helfen damit Pflanzen beim Wachsen.',
    'molecule.hydrogenPeroxide.name': 'Wasserstoffperoxid',
    'molecule.hydrogenPeroxide.fact': 'Wie Wasser, nur mit einem Sauerstoff mehr. Es schäumt, wenn es eine Schramme sauber macht.',
    'molecule.acetylene.name': 'Acetylen',
    'molecule.acetylene.fact': 'Seine Flamme ist so heiß, dass Schweißer damit Metall schneiden und verbinden.',
    'molecule.methane.name': 'Methan',
    'molecule.methane.fact': 'Das Gas in vielen Küchenherden. Kühe rülpsen es auch aus!',
    'molecule.ethylene.name': 'Ethylen',
    'molecule.ethylene.fact': 'Obst gibt es beim Reifen ab. Eine Banane lässt das Obst daneben schneller reif werden!',
    'molecule.urea.name': 'Harnstoff',
    'molecule.urea.fact': 'Dein Körper macht ihn, um überschüssigen Stickstoff loszuwerden. Er ist im Pipi!',
    'molecule.aceticAcid.name': 'Essigsäure',
    'molecule.aceticAcid.fact': 'Sie macht Essig sauer und gibt ihm seinen scharfen Geruch.',
    'molecule.glycine.name': 'Glycin',
    'molecule.glycine.fact': 'Der kleinste der Bausteine, aus denen die Eiweiße in deinem Körper bestehen.',
    'molecule.propane.name': 'Propan',
    'molecule.propane.fact': 'Das Gas in Grillflaschen. Es ist so fest zusammengepresst, dass es flüssig wird.',
    'molecule.benzene.name': 'Benzol',
    'molecule.benzene.fact': 'Sechs Kohlenstoffe halten sich im Kreis an den Händen. Ein Forscher träumte von einer Schlange, die sich in den Schwanz beißt, und erriet so die Form!',
  },
});
