// Dice Thrower texts. Cheers are separated by "|"; one is picked at random.

import { addStrings } from '../../shared/i18n.js';

addStrings({
  en: {
    'dice.pageTitle': 'Dice Thrower · Playbox',
    'dice.chooseBuddy': 'Choose your buddy',
    'dice.chooseLook': 'Choose a look',
    'dice.table': 'Dice table',
    'dice.rollTheDice': 'Roll the dice',
    'dice.howMany': 'How many dice',
    'dice.oneLess': 'One less die',
    'dice.oneMore': 'One more die',
    'dice.count': { one: '{count} die', other: '{count} dice' },
    'dice.roll': 'Roll!',
    'dice.rolling': 'Rolling…',
    'dice.start': 'Tap Roll to throw the dice!',
    'dice.youRolled': 'You rolled {value}.',
    'dice.lastTime': 'Last time: {roll}',
    'dice.newBest': 'New best!',
    'dice.allClear': 'All clear! Roll again.',
    'dice.yourRolls': 'Your rolls',
    'dice.rolls': 'Rolls',
    'dice.bestTotal': 'Best total',
    'dice.lastRolls': 'Last rolls',
    'dice.noRolls': 'No rolls yet.',
    'dice.howOften': 'How often each number came up',
    'dice.faceCount': { one: '{face}: {count} time', other: '{face}: {count} times' },
    'dice.music': 'Music',
    'dice.musicOn': 'Music is on. Turn music off',
    'dice.musicOff': 'Music is off. Turn music on',
    'char.princess.name': 'Princess',
    'char.princess.cheers': 'Royal roll!|Sparkle power!|How magical!|Fit for a queen!',
    'char.prince.name': 'Prince',
    'char.prince.cheers': 'Royal roll!|Hear ye, hear ye!|By royal decree!|A noble number!',
    'char.cowboy.name': 'Cowboy',
    'char.cowboy.cheers': 'Yee-haw!|Nice throw, partner!|Rootin’ tootin’!|Giddy-up!',
    'char.cowgirl.name': 'Cowgirl',
    'char.cowgirl.cheers': 'Yee-haw!|Nice throw, partner!|Ride ’em!|Howdy, lucky!',
    'char.explorer.name': 'Explorer',
    'char.explorer.cheers': 'Treasure found!|What an adventure!|X marks the spot!|Great discovery!',
    'char.adventurer.name': 'Adventurer',
    'char.adventurer.cheers': 'Relic found!|Into the ruins!|Ancient luck!|Tomb treasure!',
    'char.pixel.name': 'Pixel Boy',
    'char.pixel.cheers': 'Level up!|Critical roll!|+1 XP!|Block party!',
    'char.pixel-girl.name': 'Pixel Girl',
    'char.pixel-girl.cheers': 'Level up!|High score!|+1 XP!|Power-up!',
    'char.witch.name': 'Witch',
    'char.witch.cheers': 'Abracadabra!|Hocus pocus!|Spell success!|Magic number!',
    'char.wizard.name': 'Wizard',
    'char.wizard.cheers': 'Alakazam!|By my beard!|Arcane roll!|Wizardly!',
  },
  it: {
    'dice.pageTitle': 'Lancia i dadi · Playbox',
    'dice.chooseBuddy': 'Scegli il tuo amico',
    'dice.chooseLook': 'Scegli un aspetto',
    'dice.table': 'Tavolo dei dadi',
    'dice.rollTheDice': 'Lancia i dadi',
    'dice.howMany': 'Quanti dadi',
    'dice.oneLess': 'Un dado in meno',
    'dice.oneMore': 'Un dado in più',
    'dice.count': { one: '{count} dado', other: '{count} dadi' },
    'dice.roll': 'Lancia!',
    'dice.rolling': 'Lancio…',
    'dice.start': 'Tocca Lancia per tirare i dadi!',
    'dice.youRolled': 'Hai fatto {value}.',
    'dice.lastTime': 'L’ultima volta: {roll}',
    'dice.newBest': 'Nuovo record!',
    'dice.allClear': 'Tutto pulito! Lancia ancora.',
    'dice.yourRolls': 'I tuoi lanci',
    'dice.rolls': 'Lanci',
    'dice.bestTotal': 'Totale migliore',
    'dice.lastRolls': 'Ultimi lanci',
    'dice.noRolls': 'Ancora nessun lancio.',
    'dice.howOften': 'Quante volte è uscito ogni numero',
    'dice.faceCount': { one: '{face}: {count} volta', other: '{face}: {count} volte' },
    'dice.music': 'Musica',
    'dice.musicOn': 'Musica accesa. Spegni la musica',
    'dice.musicOff': 'Musica spenta. Accendi la musica',
    'char.princess.name': 'Principessa',
    'char.princess.cheers': 'Lancio reale!|Magia scintillante!|Che magia!|Degno di una regina!',
    'char.prince.name': 'Principe',
    'char.prince.cheers': 'Lancio reale!|Udite, udite!|Per decreto reale!|Un numero nobile!',
    'char.cowboy.name': 'Cowboy',
    'char.cowboy.cheers': 'Yee-haw!|Bel lancio, socio!|Alla carica!|Via, cavallo!',
    'char.cowgirl.name': 'Cowgirl',
    'char.cowgirl.cheers': 'Yee-haw!|Bel lancio, socio!|In sella!|Che fortuna!',
    'char.explorer.name': 'Esploratore',
    'char.explorer.cheers': 'Tesoro trovato!|Che avventura!|La X segna il punto!|Grande scoperta!',
    'char.adventurer.name': 'Avventuriera',
    'char.adventurer.cheers': 'Reliquia trovata!|Dentro le rovine!|Fortuna antica!|Tesoro della tomba!',
    'char.pixel.name': 'Ragazzo Pixel',
    'char.pixel.cheers': 'Livello su!|Lancio critico!|+1 XP!|Festa dei blocchi!',
    'char.pixel-girl.name': 'Ragazza Pixel',
    'char.pixel-girl.cheers': 'Livello su!|Punteggio record!|+1 XP!|Potenziamento!',
    'char.witch.name': 'Strega',
    'char.witch.cheers': 'Abracadabra!|Hocus pocus!|Incantesimo riuscito!|Numero magico!',
    'char.wizard.name': 'Mago',
    'char.wizard.cheers': 'Alakazam!|Per la mia barba!|Lancio arcano!|Da vero mago!',
  },
  es: {
    'dice.pageTitle': 'Lanzadados · Playbox',
    'dice.chooseBuddy': 'Elige a tu amigo',
    'dice.chooseLook': 'Elige un aspecto',
    'dice.table': 'Mesa de dados',
    'dice.rollTheDice': 'Lanzar los dados',
    'dice.howMany': 'Cuántos dados',
    'dice.oneLess': 'Un dado menos',
    'dice.oneMore': 'Un dado más',
    'dice.count': { one: '{count} dado', other: '{count} dados' },
    'dice.roll': '¡Lanzar!',
    'dice.rolling': 'Lanzando…',
    'dice.start': '¡Toca Lanzar para tirar los dados!',
    'dice.youRolled': 'Sacaste {value}.',
    'dice.lastTime': 'La última vez: {roll}',
    'dice.newBest': '¡Nuevo récord!',
    'dice.allClear': '¡Todo borrado! Lanza otra vez.',
    'dice.yourRolls': 'Tus tiradas',
    'dice.rolls': 'Tiradas',
    'dice.bestTotal': 'Mejor total',
    'dice.lastRolls': 'Últimas tiradas',
    'dice.noRolls': 'Aún no hay tiradas.',
    'dice.howOften': 'Cuántas veces salió cada número',
    'dice.faceCount': { one: '{face}: {count} vez', other: '{face}: {count} veces' },
    'dice.music': 'Música',
    'dice.musicOn': 'Música activada. Quitar la música',
    'dice.musicOff': 'Música desactivada. Poner la música',
    'char.princess.name': 'Princesa',
    'char.princess.cheers': '¡Tirada real!|¡Poder brillante!|¡Qué mágico!|¡Digno de una reina!',
    'char.prince.name': 'Príncipe',
    'char.prince.cheers': '¡Tirada real!|¡Oíd, oíd!|¡Por decreto real!|¡Un número noble!',
    'char.cowboy.name': 'Vaquero',
    'char.cowboy.cheers': '¡Yiijaa!|¡Buen tiro, compañero!|¡Arre, caballo!|¡Al galope!',
    'char.cowgirl.name': 'Vaquera',
    'char.cowgirl.cheers': '¡Yiijaa!|¡Buen tiro, compañera!|¡A cabalgar!|¡Qué suerte!',
    'char.explorer.name': 'Explorador',
    'char.explorer.cheers': '¡Tesoro encontrado!|¡Qué aventura!|¡La X marca el lugar!|¡Gran descubrimiento!',
    'char.adventurer.name': 'Aventurera',
    'char.adventurer.cheers': '¡Reliquia encontrada!|¡A las ruinas!|¡Suerte antigua!|¡Tesoro de la tumba!',
    'char.pixel.name': 'Chico Píxel',
    'char.pixel.cheers': '¡Subes de nivel!|¡Tirada crítica!|¡+1 XP!|¡Fiesta de bloques!',
    'char.pixel-girl.name': 'Chica Píxel',
    'char.pixel-girl.cheers': '¡Subes de nivel!|¡Récord!|¡+1 XP!|¡Poder extra!',
    'char.witch.name': 'Bruja',
    'char.witch.cheers': '¡Abracadabra!|¡Hocus pocus!|¡Hechizo logrado!|¡Número mágico!',
    'char.wizard.name': 'Mago',
    'char.wizard.cheers': '¡Alakazam!|¡Por mis barbas!|¡Tirada arcana!|¡Qué mago!',
  },
  'pt-BR': {
    'dice.pageTitle': 'Lança Dados · Playbox',
    'dice.chooseBuddy': 'Escolha seu amigo',
    'dice.chooseLook': 'Escolha um visual',
    'dice.table': 'Mesa de dados',
    'dice.rollTheDice': 'Jogar os dados',
    'dice.howMany': 'Quantos dados',
    'dice.oneLess': 'Um dado a menos',
    'dice.oneMore': 'Um dado a mais',
    'dice.count': { one: '{count} dado', other: '{count} dados' },
    'dice.roll': 'Jogar!',
    'dice.rolling': 'Jogando…',
    'dice.start': 'Toque em Jogar para lançar os dados!',
    'dice.youRolled': 'Você tirou {value}.',
    'dice.lastTime': 'Da última vez: {roll}',
    'dice.newBest': 'Novo recorde!',
    'dice.allClear': 'Tudo limpo! Jogue de novo.',
    'dice.yourRolls': 'Suas jogadas',
    'dice.rolls': 'Jogadas',
    'dice.bestTotal': 'Melhor total',
    'dice.lastRolls': 'Últimas jogadas',
    'dice.noRolls': 'Nenhuma jogada ainda.',
    'dice.howOften': 'Quantas vezes saiu cada número',
    'dice.faceCount': { one: '{face}: {count} vez', other: '{face}: {count} vezes' },
    'dice.music': 'Música',
    'dice.musicOn': 'Música ligada. Desligar a música',
    'dice.musicOff': 'Música desligada. Ligar a música',
    'char.princess.name': 'Princesa',
    'char.princess.cheers': 'Jogada real!|Poder brilhante!|Que mágico!|Digno de uma rainha!',
    'char.prince.name': 'Príncipe',
    'char.prince.cheers': 'Jogada real!|Ouçam, ouçam!|Por decreto real!|Um número nobre!',
    'char.cowboy.name': 'Caubói',
    'char.cowboy.cheers': 'Iiiirrá!|Boa jogada, parceiro!|Upa, cavalinho!|A galope!',
    'char.cowgirl.name': 'Vaqueira',
    'char.cowgirl.cheers': 'Iiiirrá!|Boa jogada, parceira!|Vamos cavalgar!|Que sorte!',
    'char.explorer.name': 'Explorador',
    'char.explorer.cheers': 'Tesouro encontrado!|Que aventura!|O X marca o lugar!|Grande descoberta!',
    'char.adventurer.name': 'Aventureira',
    'char.adventurer.cheers': 'Relíquia encontrada!|Para as ruínas!|Sorte antiga!|Tesouro da tumba!',
    'char.pixel.name': 'Menino Pixel',
    'char.pixel.cheers': 'Subiu de nível!|Jogada crítica!|+1 XP!|Festa dos blocos!',
    'char.pixel-girl.name': 'Menina Pixel',
    'char.pixel-girl.cheers': 'Subiu de nível!|Recorde!|+1 XP!|Poder extra!',
    'char.witch.name': 'Bruxa',
    'char.witch.cheers': 'Abracadabra!|Hocus pocus!|Feitiço certeiro!|Número mágico!',
    'char.wizard.name': 'Mago',
    'char.wizard.cheers': 'Alakazam!|Pelas minhas barbas!|Jogada arcana!|Coisa de mago!',
  },
  de: {
    'dice.pageTitle': 'Würfelwerfer · Playbox',
    'dice.chooseBuddy': 'Wähle deinen Freund',
    'dice.chooseLook': 'Wähle ein Aussehen',
    'dice.table': 'Würfeltisch',
    'dice.rollTheDice': 'Würfeln',
    'dice.howMany': 'Wie viele Würfel',
    'dice.oneLess': 'Ein Würfel weniger',
    'dice.oneMore': 'Ein Würfel mehr',
    'dice.count': { one: '{count} Würfel', other: '{count} Würfel' },
    'dice.roll': 'Würfeln!',
    'dice.rolling': 'Es rollt…',
    'dice.start': 'Tippe auf Würfeln!',
    'dice.youRolled': 'Du hast eine {value} gewürfelt.',
    'dice.lastTime': 'Letztes Mal: {roll}',
    'dice.newBest': 'Neuer Rekord!',
    'dice.allClear': 'Alles gelöscht! Würfle nochmal.',
    'dice.yourRolls': 'Deine Würfe',
    'dice.rolls': 'Würfe',
    'dice.bestTotal': 'Beste Summe',
    'dice.lastRolls': 'Letzte Würfe',
    'dice.noRolls': 'Noch keine Würfe.',
    'dice.howOften': 'Wie oft jede Zahl kam',
    'dice.faceCount': { one: '{face}: {count}-mal', other: '{face}: {count}-mal' },
    'dice.music': 'Musik',
    'dice.musicOn': 'Musik ist an. Musik ausschalten',
    'dice.musicOff': 'Musik ist aus. Musik einschalten',
    'char.princess.name': 'Prinzessin',
    'char.princess.cheers': 'Königlicher Wurf!|Glitzerkraft!|Wie magisch!|Einer Königin würdig!',
    'char.prince.name': 'Prinz',
    'char.prince.cheers': 'Königlicher Wurf!|Hört, hört!|Auf königlichen Befehl!|Eine edle Zahl!',
    'char.cowboy.name': 'Cowboy',
    'char.cowboy.cheers': 'Yee-haw!|Guter Wurf, Partner!|Hü, hott!|Im Galopp!',
    'char.cowgirl.name': 'Cowgirl',
    'char.cowgirl.cheers': 'Yee-haw!|Guter Wurf, Partner!|Aufsatteln!|Was für ein Glück!',
    'char.explorer.name': 'Entdecker',
    'char.explorer.cheers': 'Schatz gefunden!|Was für ein Abenteuer!|X markiert die Stelle!|Tolle Entdeckung!',
    'char.adventurer.name': 'Abenteurerin',
    'char.adventurer.cheers': 'Relikt gefunden!|Ab in die Ruine!|Uraltes Glück!|Grabschatz!',
    'char.pixel.name': 'Pixel-Junge',
    'char.pixel.cheers': 'Level up!|Kritischer Wurf!|+1 EP!|Blockparty!',
    'char.pixel-girl.name': 'Pixel-Mädchen',
    'char.pixel-girl.cheers': 'Level up!|Highscore!|+1 EP!|Power-up!',
    'char.witch.name': 'Hexe',
    'char.witch.cheers': 'Abrakadabra!|Hokuspokus!|Zauber gelungen!|Zauberzahl!',
    'char.wizard.name': 'Zauberer',
    'char.wizard.cheers': 'Simsalabim!|Bei meinem Bart!|Magischer Wurf!|Zauberhaft!',
  },
});
