// Blocks texts.

import { addStrings } from '../../shared/i18n.js';

addStrings({
  en: {
    'blocks.pageTitle': 'Blocks · Playbox',
    'blocks.area': 'Building area. Tap to add a block, drag to look around, pinch or use the zoom buttons to zoom.',
    'blocks.loading': 'Getting the blocks ready…',
    'blocks.noWebgl': 'This device can’t show 3D right now. Try another browser.',
    'blocks.undo': 'Undo',
    'blocks.undoTitle': 'Undo (Ctrl+Z)',
    'blocks.tapAgain': 'Tap again',
    'blocks.timeOfDay': 'Time of day',
    'blocks.matchClock': 'Match my clock',
    'blocks.hint': 'Tap to build · Drag to look around · Pinch to zoom',
    'blocks.toolGroup': 'Tool',
    'blocks.tool.build': 'Build',
    'blocks.tool.paint': 'Paint',
    'blocks.tool.remove': 'Remove',
    'blocks.turn': '⟳ Turn',
    'blocks.turnTitle': 'Turn the block (R)',
    'blocks.lookGroup': 'Look',
    'blocks.finish.plain': 'Plain',
    'blocks.finish.textured': 'Textured',
    'blocks.shapeGroup': 'Block shape',
    'blocks.colorGroup': 'Color',
    'blocks.textureGroup': 'Texture',
    'blocks.tab.shape': 'Shape',
    'blocks.tab.color': 'Color',
    'blocks.tab.look': 'Look',
    'blocks.colorNamed': 'Color {hex}',
    'blocks.anyColor': 'Pick any color',
    'blocks.time.sunrise': 'Sunrise',
    'blocks.time.morning': 'Morning',
    'blocks.time.noon': 'Noon',
    'blocks.time.afternoon': 'Afternoon',
    'blocks.time.sunset': 'Sunset',
    'blocks.time.evening': 'Evening',
    'blocks.time.night': 'Night',
    'blocks.shape.brick': 'Brick',
    'blocks.shape.long': 'Long',
    'blocks.shape.square': 'Square',
    'blocks.shape.plank': 'Plank',
    'blocks.shape.ramp': 'Ramp',
    'blocks.shape.round': 'Round',
    'blocks.shape.cone': 'Cone',
    'blocks.shape.arch': 'Arch',
    'blocks.shape.dome': 'Dome',
    'blocks.texture.brick': 'Brick',
    'blocks.texture.stone': 'Stone',
    'blocks.texture.wood': 'Wood',
    'blocks.texture.marble': 'Marble',
    'blocks.texture.metal': 'Metal',
    'blocks.texture.fabric': 'Wool',
    'blocks.texture.tiles': 'Tiles',
    'blocks.texture.leaves': 'Leaves',
  },
  it: {
    'blocks.pageTitle': 'Mattoncini · Playbox',
    'blocks.area': 'Area di costruzione. Tocca per aggiungere un mattoncino, trascina per guardarti intorno, pizzica o usa i pulsanti per lo zoom.',
    'blocks.loading': 'Preparo i mattoncini…',
    'blocks.noWebgl': 'Questo dispositivo ora non riesce a mostrare il 3D. Prova un altro browser.',
    'blocks.undo': 'Annulla',
    'blocks.undoTitle': 'Annulla (Ctrl+Z)',
    'blocks.tapAgain': 'Tocca ancora',
    'blocks.timeOfDay': 'Ora del giorno',
    'blocks.matchClock': 'Segui il mio orologio',
    'blocks.hint': 'Tocca per costruire · Trascina per guardare · Pizzica per lo zoom',
    'blocks.toolGroup': 'Strumento',
    'blocks.tool.build': 'Costruisci',
    'blocks.tool.paint': 'Colora',
    'blocks.tool.remove': 'Togli',
    'blocks.turn': '⟳ Gira',
    'blocks.turnTitle': 'Gira il mattoncino (R)',
    'blocks.lookGroup': 'Aspetto',
    'blocks.finish.plain': 'Semplice',
    'blocks.finish.textured': 'Materiali',
    'blocks.shapeGroup': 'Forma del mattoncino',
    'blocks.colorGroup': 'Colore',
    'blocks.textureGroup': 'Materiale',
    'blocks.tab.shape': 'Forma',
    'blocks.tab.color': 'Colore',
    'blocks.tab.look': 'Aspetto',
    'blocks.colorNamed': 'Colore {hex}',
    'blocks.anyColor': 'Scegli un colore qualsiasi',
    'blocks.time.sunrise': 'Alba',
    'blocks.time.morning': 'Mattina',
    'blocks.time.noon': 'Mezzogiorno',
    'blocks.time.afternoon': 'Pomeriggio',
    'blocks.time.sunset': 'Tramonto',
    'blocks.time.evening': 'Sera',
    'blocks.time.night': 'Notte',
    'blocks.shape.brick': 'Mattone',
    'blocks.shape.long': 'Lungo',
    'blocks.shape.square': 'Quadrato',
    'blocks.shape.plank': 'Asse',
    'blocks.shape.ramp': 'Rampa',
    'blocks.shape.round': 'Tondo',
    'blocks.shape.cone': 'Cono',
    'blocks.shape.arch': 'Arco',
    'blocks.shape.dome': 'Cupola',
    'blocks.texture.brick': 'Mattoni',
    'blocks.texture.stone': 'Pietra',
    'blocks.texture.wood': 'Legno',
    'blocks.texture.marble': 'Marmo',
    'blocks.texture.metal': 'Metallo',
    'blocks.texture.fabric': 'Lana',
    'blocks.texture.tiles': 'Piastrelle',
    'blocks.texture.leaves': 'Foglie',
  },
  es: {
    'blocks.pageTitle': 'Bloques · Playbox',
    'blocks.area': 'Zona de construcción. Toca para poner un bloque, arrastra para mirar alrededor, pellizca o usa los botones para hacer zoom.',
    'blocks.loading': 'Preparando los bloques…',
    'blocks.noWebgl': 'Este dispositivo no puede mostrar 3D ahora. Prueba otro navegador.',
    'blocks.undo': 'Deshacer',
    'blocks.undoTitle': 'Deshacer (Ctrl+Z)',
    'blocks.tapAgain': 'Toca otra vez',
    'blocks.timeOfDay': 'Hora del día',
    'blocks.matchClock': 'Usar mi reloj',
    'blocks.hint': 'Toca para construir · Arrastra para mirar · Pellizca para hacer zoom',
    'blocks.toolGroup': 'Herramienta',
    'blocks.tool.build': 'Construir',
    'blocks.tool.paint': 'Pintar',
    'blocks.tool.remove': 'Quitar',
    'blocks.turn': '⟳ Girar',
    'blocks.turnTitle': 'Girar el bloque (R)',
    'blocks.lookGroup': 'Aspecto',
    'blocks.finish.plain': 'Liso',
    'blocks.finish.textured': 'Materiales',
    'blocks.shapeGroup': 'Forma del bloque',
    'blocks.colorGroup': 'Color',
    'blocks.textureGroup': 'Material',
    'blocks.tab.shape': 'Forma',
    'blocks.tab.color': 'Color',
    'blocks.tab.look': 'Aspecto',
    'blocks.colorNamed': 'Color {hex}',
    'blocks.anyColor': 'Elige cualquier color',
    'blocks.time.sunrise': 'Amanecer',
    'blocks.time.morning': 'Mañana',
    'blocks.time.noon': 'Mediodía',
    'blocks.time.afternoon': 'Tarde',
    'blocks.time.sunset': 'Atardecer',
    'blocks.time.evening': 'Anochecer',
    'blocks.time.night': 'Noche',
    'blocks.shape.brick': 'Ladrillo',
    'blocks.shape.long': 'Largo',
    'blocks.shape.square': 'Cuadrado',
    'blocks.shape.plank': 'Tabla',
    'blocks.shape.ramp': 'Rampa',
    'blocks.shape.round': 'Redondo',
    'blocks.shape.cone': 'Cono',
    'blocks.shape.arch': 'Arco',
    'blocks.shape.dome': 'Cúpula',
    'blocks.texture.brick': 'Ladrillo',
    'blocks.texture.stone': 'Piedra',
    'blocks.texture.wood': 'Madera',
    'blocks.texture.marble': 'Mármol',
    'blocks.texture.metal': 'Metal',
    'blocks.texture.fabric': 'Lana',
    'blocks.texture.tiles': 'Azulejos',
    'blocks.texture.leaves': 'Hojas',
  },
  'pt-BR': {
    'blocks.pageTitle': 'Blocos · Playbox',
    'blocks.area': 'Área de construção. Toque para colocar um bloco, arraste para olhar em volta, faça pinça ou use os botões para dar zoom.',
    'blocks.loading': 'Preparando os blocos…',
    'blocks.noWebgl': 'Este aparelho não consegue mostrar 3D agora. Tente outro navegador.',
    'blocks.undo': 'Desfazer',
    'blocks.undoTitle': 'Desfazer (Ctrl+Z)',
    'blocks.tapAgain': 'Toque de novo',
    'blocks.timeOfDay': 'Hora do dia',
    'blocks.matchClock': 'Usar meu relógio',
    'blocks.hint': 'Toque para construir · Arraste para olhar · Faça pinça para dar zoom',
    'blocks.toolGroup': 'Ferramenta',
    'blocks.tool.build': 'Construir',
    'blocks.tool.paint': 'Pintar',
    'blocks.tool.remove': 'Tirar',
    'blocks.turn': '⟳ Girar',
    'blocks.turnTitle': 'Girar o bloco (R)',
    'blocks.lookGroup': 'Visual',
    'blocks.finish.plain': 'Liso',
    'blocks.finish.textured': 'Materiais',
    'blocks.shapeGroup': 'Forma do bloco',
    'blocks.colorGroup': 'Cor',
    'blocks.textureGroup': 'Material',
    'blocks.tab.shape': 'Forma',
    'blocks.tab.color': 'Cor',
    'blocks.tab.look': 'Visual',
    'blocks.colorNamed': 'Cor {hex}',
    'blocks.anyColor': 'Escolha qualquer cor',
    'blocks.time.sunrise': 'Nascer do sol',
    'blocks.time.morning': 'Manhã',
    'blocks.time.noon': 'Meio-dia',
    'blocks.time.afternoon': 'Tarde',
    'blocks.time.sunset': 'Pôr do sol',
    'blocks.time.evening': 'Anoitecer',
    'blocks.time.night': 'Noite',
    'blocks.shape.brick': 'Tijolo',
    'blocks.shape.long': 'Comprido',
    'blocks.shape.square': 'Quadrado',
    'blocks.shape.plank': 'Tábua',
    'blocks.shape.ramp': 'Rampa',
    'blocks.shape.round': 'Redondo',
    'blocks.shape.cone': 'Cone',
    'blocks.shape.arch': 'Arco',
    'blocks.shape.dome': 'Cúpula',
    'blocks.texture.brick': 'Tijolo',
    'blocks.texture.stone': 'Pedra',
    'blocks.texture.wood': 'Madeira',
    'blocks.texture.marble': 'Mármore',
    'blocks.texture.metal': 'Metal',
    'blocks.texture.fabric': 'Lã',
    'blocks.texture.tiles': 'Azulejos',
    'blocks.texture.leaves': 'Folhas',
  },
  de: {
    'blocks.pageTitle': 'Bausteine · Playbox',
    'blocks.area': 'Baufläche. Tippe, um einen Stein zu setzen, zieh, um dich umzuschauen, und zoome mit zwei Fingern oder den Knöpfen.',
    'blocks.loading': 'Die Steine werden vorbereitet…',
    'blocks.noWebgl': 'Dieses Gerät kann gerade kein 3D zeigen. Probier einen anderen Browser.',
    'blocks.undo': 'Rückgängig',
    'blocks.undoTitle': 'Rückgängig (Strg+Z)',
    'blocks.tapAgain': 'Nochmal tippen',
    'blocks.timeOfDay': 'Tageszeit',
    'blocks.matchClock': 'Wie meine Uhr',
    'blocks.hint': 'Tippen zum Bauen · Ziehen zum Umschauen · Zwei Finger zum Zoomen',
    'blocks.toolGroup': 'Werkzeug',
    'blocks.tool.build': 'Bauen',
    'blocks.tool.paint': 'Malen',
    'blocks.tool.remove': 'Entfernen',
    'blocks.turn': '⟳ Drehen',
    'blocks.turnTitle': 'Stein drehen (R)',
    'blocks.lookGroup': 'Aussehen',
    'blocks.finish.plain': 'Einfach',
    'blocks.finish.textured': 'Materialien',
    'blocks.shapeGroup': 'Steinform',
    'blocks.colorGroup': 'Farbe',
    'blocks.textureGroup': 'Material',
    'blocks.tab.shape': 'Form',
    'blocks.tab.color': 'Farbe',
    'blocks.tab.look': 'Aussehen',
    'blocks.colorNamed': 'Farbe {hex}',
    'blocks.anyColor': 'Beliebige Farbe wählen',
    'blocks.time.sunrise': 'Sonnenaufgang',
    'blocks.time.morning': 'Morgen',
    'blocks.time.noon': 'Mittag',
    'blocks.time.afternoon': 'Nachmittag',
    'blocks.time.sunset': 'Sonnenuntergang',
    'blocks.time.evening': 'Abend',
    'blocks.time.night': 'Nacht',
    'blocks.shape.brick': 'Stein',
    'blocks.shape.long': 'Lang',
    'blocks.shape.square': 'Quadrat',
    'blocks.shape.plank': 'Brett',
    'blocks.shape.ramp': 'Rampe',
    'blocks.shape.round': 'Rund',
    'blocks.shape.cone': 'Kegel',
    'blocks.shape.arch': 'Bogen',
    'blocks.shape.dome': 'Kuppel',
    'blocks.texture.brick': 'Ziegel',
    'blocks.texture.stone': 'Stein',
    'blocks.texture.wood': 'Holz',
    'blocks.texture.marble': 'Marmor',
    'blocks.texture.metal': 'Metall',
    'blocks.texture.fabric': 'Wolle',
    'blocks.texture.tiles': 'Fliesen',
    'blocks.texture.leaves': 'Blätter',
  },
});
