// Release notes for What's new, in every language. They're not part of
// the first download (the app's shell): the home page loads this file in the
// background on Wi-Fi, or when What's new is opened. Add each release's
// notes here (keys match shared/changelog.js).

import { addStrings } from '../shared/i18n.js';

addStrings({
  en: {
    'changes.v6.fullscreen': 'Every game has a full-screen button, to use the whole phone or tablet screen.',
    'changes.v12.installedTop': 'When Playbox is added to the iPhone Home Screen, the top of the screen no longer looks blurry.',
    'changes.v13.molecules': 'A brand-new game! Join atoms to build molecules, from water to benzene. Easy mode shows the picture; hard mode only the name.',
    'changes.v14.drive': 'A brand-new game! Drive shiny supercars through a neon city, a jungle and a snowy wasteland that turns into desert, and collect all the points. Harder levels put them at the edges and in the bends.',
    'changes.v15.driveLooks': 'Turbo Drive looks like a console game now: sharper textures, real shadows, glowing neon and lights, a sky with sun, clouds and stars, shiny cars that reflect it, and smoke, dust, snow and sparks from the wheels.',
    'changes.v16.fastUpdate': 'After an update, games open right away again, instead of waiting until every saved game has downloaded. Games that got new files stay saved for offline, too.',
    'changes.v16.driveMusic': 'Every track has its own music (with a button to turn it off), the engine is quieter, and the pads moved: steering at the edges, with brake and nitro in the middle on a tall screen, or next to the steering on a wide one.',
    'changes.v17.steerYourself': 'No more self-steering: the car only turns when you steer, so staying on the road is up to you.',
    'changes.v17.rotate': 'Turning the phone in the installed app no longer leaves part of the screen under the notch, and in landscape everything stays clear of it.',
    'changes.v18.trackBuilder': 'Build your own tracks! Add straights and curves, pick the city, jungle or wasteland, and drive them. The end joins back to the start by itself, tracks can be as long as you like, and you can share them as a file or a code.',
    'changes.v18.barriers': 'Barriers no longer turn the car along the road: scraping one slows you to a crawl until you steer away.',
    'changes.v19.boostPads': 'No more nitro and brake buttons: drive over the glowing blue arrows on the road for a burst of nitro. Just steer!',
    'changes.v20.tilt': 'Steer by tilting the phone like a steering wheel (choose it under Steering in the garage). Tap the screen to straighten up.',
    'changes.v20.customize': 'Customize your car: glossy, matte or chrome paint, racing stripes, wheel colors, a wing and a colored underglow.',
    'changes.v21.autoUpdate': 'Updates now show up by themselves: the app reloads when you come back to it, or right away if you aren\'t playing, instead of needing to be closed and opened again.',
    'changes.v21.lighterStart': 'A lighter first visit: these notes now load only when you read them, or in the background on Wi-Fi.',
    'changes.v22.promise': 'Every page now says it plainly: no ads, no tracking, your games and scores stay on this device, and the code is open source on GitHub.',
    'changes.v23.looks': 'New car looks: five street racer presets, plus side graphics (swooshes, tribal or flames), a hood scoop or supercharger, silver, lime and hot pink paint, and blue underglow.',
    'changes.v11.versionSpace': 'More space above the version number at the bottom of the page.',
    'changes.v10.iosTop': 'On iPhone, nothing slides under the clock anymore, so the top of the screen stays clear.',
    'changes.v10.footer': 'More room at the bottom of the page, so the version number isn’t hidden.',
    'changes.v10.firefox': 'Rounded corners on the 3D view in Firefox.',
    'changes.v9.iosBlur': 'On iPhone, full screen keeps the game from sliding under the blurry area behind the clock.',
    'changes.v8.version': 'The bottom of every page shows the version number, so you can tell if you have the latest.',
    'changes.v7.focus': 'Full screen now uses the whole screen: the top bar goes away and its buttons move into the game.',
    'changes.v7.blocksPhones': 'Fits phones better: one palette at a time, a small time-of-day button, and tools on the side when the phone is sideways.',
    'changes.v6.whatsNew': '“What’s new” shows which games were added or updated.',
    'changes.v6.updateNotice': 'Playbox tells you when an update is ready.',
    'changes.v5.languages': 'Playbox now speaks English, Italian, Spanish, Brazilian Portuguese and German.',
    'changes.v4.memory': 'A brand-new game! Flip cards with animals, planets, flags or your own photos.',
    'changes.v4.blocks': 'A brand-new game! Build anything in 3D, from sunrise to a starry night.',
    'changes.v4.offline': 'Faster first visit. Games are saved for offline use when you open them.',
    'changes.v4.mageDice': 'The witch’s and wizard’s dice are 3D again.',
    'changes.v3.looks': 'Every buddy has a second look, each with its own scene: Prince, Cowgirl, Adventurer and Pixel Girl.',
    'changes.v3.mage': 'A new buddy: the Witch, or the Wizard.',
    'changes.v2.music': 'Every buddy has its own music, with a button to turn it off.',
    'changes.v1.dice': 'The very first game, with four buddies to throw the dice.',
  },
  it: {
    'changes.v6.fullscreen': 'Ogni gioco ha un pulsante per lo schermo intero, per usare tutto lo schermo di telefono o tablet.',
    'changes.v12.installedTop': 'Con Playbox aggiunto alla schermata Home dell’iPhone, la parte alta dello schermo non è più sfocata.',
    'changes.v13.molecules': 'Un gioco tutto nuovo! Unisci gli atomi per costruire molecole, dall’acqua al benzene. In modalità facile vedi il disegno, in quella difficile solo il nome.',
    'changes.v14.drive': 'Un gioco tutto nuovo! Guida supercar lucenti in una città al neon, nella giungla e in terre desolate innevate che diventano deserto, e raccogli tutti i punti. Nei livelli più difficili sono sui bordi e nelle curve.',
    'changes.v15.driveLooks': 'Turbo Drive ora sembra un gioco da console: texture più nitide, ombre vere, neon e luci che brillano, un cielo con sole, nuvole e stelle, auto lucide che lo riflettono, e fumo, polvere, neve e scintille dalle ruote.',
    'changes.v16.fastUpdate': 'Dopo un aggiornamento i giochi si aprono subito, senza aspettare che tutti i giochi salvati siano scaricati. Anche i giochi con file nuovi restano salvati per l’uso offline.',
    'changes.v16.driveMusic': 'Ogni pista ha la sua musica (con un pulsante per spegnerla), il motore è più silenzioso e i comandi si sono spostati: sterzo ai lati, con freno e nitro al centro sullo schermo verticale, o accanto allo sterzo su quello orizzontale.',
    'changes.v17.steerYourself': 'Niente più sterzo automatico: l’auto gira solo quando sterzi tu, quindi restare in strada dipende da te.',
    'changes.v17.rotate': 'Girando il telefono nell’app installata, parte dello schermo non resta più sotto la tacca, e in orizzontale tutto resta lontano da lì.',
    'changes.v18.trackBuilder': 'Costruisci le tue piste! Aggiungi rettilinei e curve, scegli città, giungla o terre desolate e guidaci sopra. La fine si ricollega da sola all’inizio, le piste possono essere lunghe quanto vuoi e puoi condividerle come file o codice.',
    'changes.v18.barriers': 'Le barriere non girano più l’auto lungo la strada: se ne strisci una rallenti tantissimo finché non sterzi via.',
    'changes.v19.boostPads': 'Niente più pulsanti nitro e freno: passa sulle frecce blu luminose sulla strada per una scarica di nitro. Basta sterzare!',
    'changes.v20.tilt': 'Sterza inclinando il telefono come un volante (sceglilo in Sterzo nel garage). Tocca lo schermo per raddrizzare.',
    'changes.v20.customize': 'Personalizza l’auto: vernice lucida, opaca o cromata, strisce da corsa, colore dei cerchi, alettone e luci sotto colorate.',
    'changes.v21.autoUpdate': 'Gli aggiornamenti ora arrivano da soli: l’app si ricarica quando ci torni, o subito se non stai giocando, senza doverla chiudere e riaprire.',
    'changes.v21.lighterStart': 'Prima visita più leggera: queste novità ora si caricano solo quando le leggi, o in sottofondo con il Wi-Fi.',
    'changes.v22.promise': 'Ora ogni pagina lo dice chiaramente: niente pubblicità, nessun tracciamento, giochi e punteggi restano su questo dispositivo, e il codice è open source su GitHub.',
    'changes.v23.looks': 'Nuovi look per le auto: cinque stili da corsa su strada, più grafiche laterali (onde, tribali o fiamme), presa d’aria o compressore sul cofano, vernice argento, lime e rosa acceso, e luci sotto blu.',
    'changes.v11.versionSpace': 'Più spazio sopra il numero di versione in fondo alla pagina.',
    'changes.v10.iosTop': 'Su iPhone niente scivola più sotto l’orologio, così la parte alta dello schermo resta pulita.',
    'changes.v10.footer': 'Più spazio in fondo alla pagina, così il numero di versione non resta nascosto.',
    'changes.v10.firefox': 'Angoli arrotondati per la vista 3D su Firefox.',
    'changes.v9.iosBlur': 'Su iPhone, lo schermo intero non fa più scivolare il gioco sotto la zona sfocata dietro l’orologio.',
    'changes.v8.version': 'In fondo a ogni pagina c’è il numero di versione, così vedi se hai l’ultima.',
    'changes.v7.focus': 'Lo schermo intero ora usa tutto lo schermo: la barra in alto sparisce e i suoi pulsanti passano dentro il gioco.',
    'changes.v7.blocksPhones': 'Va meglio sui telefoni: una tavolozza alla volta, un pulsante piccolo per l’ora del giorno e gli strumenti di lato col telefono in orizzontale.',
    'changes.v6.whatsNew': '“Novità” mostra quali giochi sono stati aggiunti o aggiornati.',
    'changes.v6.updateNotice': 'Playbox ti avvisa quando c’è un aggiornamento.',
    'changes.v5.languages': 'Playbox ora parla inglese, italiano, spagnolo, portoghese brasiliano e tedesco.',
    'changes.v4.memory': 'Un gioco tutto nuovo! Gira le carte con animali, pianeti, bandiere o le tue foto.',
    'changes.v4.blocks': 'Un gioco tutto nuovo! Costruisci in 3D, dall’alba alla notte stellata.',
    'changes.v4.offline': 'Prima visita più veloce. I giochi si salvano per l’uso offline quando li apri.',
    'changes.v4.mageDice': 'I dadi della strega e del mago sono di nuovo in 3D.',
    'changes.v3.looks': 'Ogni amico ha un secondo aspetto, con la sua scena: Principe, Cowgirl, Avventuriera e Ragazza Pixel.',
    'changes.v3.mage': 'Un nuovo amico: la Strega, o il Mago.',
    'changes.v2.music': 'Ogni amico ha la sua musica, con un pulsante per spegnerla.',
    'changes.v1.dice': 'Il primissimo gioco, con quattro amici che lanciano i dadi.',
  },
  es: {
    'changes.v6.fullscreen': 'Cada juego tiene un botón de pantalla completa, para usar toda la pantalla del teléfono o la tableta.',
    'changes.v12.installedTop': 'Con Playbox añadido a la pantalla de inicio del iPhone, la parte de arriba ya no se ve borrosa.',
    'changes.v13.molecules': '¡Un juego nuevo! Une átomos para construir moléculas, del agua al benceno. En modo fácil ves el dibujo; en modo difícil, solo el nombre.',
    'changes.v14.drive': '¡Un juego nuevo! Conduce superdeportivos brillantes por una ciudad neón, la selva y una tierra baldía nevada que se convierte en desierto, y recoge todos los puntos. En los niveles difíciles están en los bordes y en las curvas.',
    'changes.v15.driveLooks': 'Turbo Drive ahora parece un juego de consola: texturas más nítidas, sombras de verdad, neones y luces que brillan, un cielo con sol, nubes y estrellas, coches brillantes que lo reflejan, y humo, polvo, nieve y chispas en las ruedas.',
    'changes.v16.fastUpdate': 'Después de una actualización, los juegos se abren enseguida, sin esperar a que se descarguen todos los juegos guardados. Los juegos con archivos nuevos también siguen guardados para usar sin conexión.',
    'changes.v16.driveMusic': 'Cada pista tiene su propia música (con un botón para apagarla), el motor suena más bajo y los botones cambiaron: el volante en los bordes, con freno y nitro en el centro en pantalla vertical, o junto al volante en horizontal.',
    'changes.v17.steerYourself': 'Se acabó el volante automático: el coche solo gira cuando tú giras, así que seguir en la carretera depende de ti.',
    'changes.v17.rotate': 'Al girar el teléfono en la app instalada, ya no queda parte de la pantalla bajo la muesca, y en horizontal todo queda lejos de ella.',
    'changes.v18.trackBuilder': '¡Construye tus propias pistas! Añade rectas y curvas, elige la ciudad, la selva o la tierra baldía y conduce por ellas. El final se une solo con la salida, pueden ser tan largas como quieras y puedes compartirlas como archivo o código.',
    'changes.v18.barriers': 'Las barreras ya no giran el coche a lo largo de la carretera: si rozas una, vas muy despacio hasta que te apartes.',
    'changes.v19.boostPads': 'Se acabaron los botones de nitro y freno: pasa por las flechas azules brillantes de la carretera para un chorro de nitro. ¡Solo gira!',
    'changes.v20.tilt': 'Gira inclinando el teléfono como un volante (elígelo en Dirección en el garaje). Toca la pantalla para enderezar.',
    'changes.v20.customize': 'Personaliza tu coche: pintura brillante, mate o cromada, franjas de carreras, color de llantas, alerón y luces de bajo de colores.',
    'changes.v21.autoUpdate': 'Las actualizaciones ahora llegan solas: la app se recarga cuando vuelves a ella, o enseguida si no estás jugando, sin tener que cerrarla y abrirla otra vez.',
    'changes.v21.lighterStart': 'Primera visita más ligera: estas novedades ahora se cargan solo cuando las lees, o en segundo plano con Wi-Fi.',
    'changes.v22.promise': 'Ahora cada página lo dice claramente: sin anuncios, sin rastreo, tus juegos y puntuaciones se quedan en este dispositivo, y el código es abierto en GitHub.',
    'changes.v23.looks': 'Nuevos looks para los coches: cinco estilos de carreras callejeras, gráficos laterales (ondas, tribal o llamas), toma de aire o compresor en el capó, pintura plateada, lima y rosa intenso, y luces de bajo azules.',
    'changes.v11.versionSpace': 'Más espacio encima del número de versión al final de la página.',
    'changes.v10.iosTop': 'En iPhone ya nada se desliza bajo el reloj, así que la parte de arriba de la pantalla queda limpia.',
    'changes.v10.footer': 'Más espacio al final de la página, para que el número de versión no quede oculto.',
    'changes.v10.firefox': 'Esquinas redondeadas en la vista 3D en Firefox.',
    'changes.v9.iosBlur': 'En iPhone, la pantalla completa ya no deja que el juego se deslice bajo la zona borrosa detrás del reloj.',
    'changes.v8.version': 'Al final de cada página aparece el número de versión, para saber si tienes la última.',
    'changes.v7.focus': 'La pantalla completa ahora usa toda la pantalla: la barra de arriba desaparece y sus botones pasan al juego.',
    'changes.v7.blocksPhones': 'Se ve mejor en teléfonos: una paleta a la vez, un botón pequeño para la hora del día y las herramientas a un lado con el teléfono en horizontal.',
    'changes.v6.whatsNew': '“Novedades” muestra qué juegos se añadieron o actualizaron.',
    'changes.v6.updateNotice': 'Playbox te avisa cuando hay una actualización.',
    'changes.v5.languages': 'Playbox ahora habla inglés, italiano, español, portugués de Brasil y alemán.',
    'changes.v4.memory': '¡Un juego totalmente nuevo! Da la vuelta a cartas con animales, planetas, banderas o tus fotos.',
    'changes.v4.blocks': '¡Un juego totalmente nuevo! Construye en 3D, del amanecer a la noche estrellada.',
    'changes.v4.offline': 'Primera visita más rápida. Los juegos se guardan para usar sin conexión al abrirlos.',
    'changes.v4.mageDice': 'Los dados de la bruja y del mago vuelven a ser 3D.',
    'changes.v3.looks': 'Cada amigo tiene un segundo aspecto, con su propio escenario: Príncipe, Vaquera, Aventurera y Chica Píxel.',
    'changes.v3.mage': 'Un amigo nuevo: la Bruja, o el Mago.',
    'changes.v2.music': 'Cada amigo tiene su propia música, con un botón para apagarla.',
    'changes.v1.dice': 'El primer juego, con cuatro amigos que lanzan los dados.',
  },
  'pt-BR': {
    'changes.v6.fullscreen': 'Cada jogo tem um botão de tela cheia, para usar a tela toda do celular ou tablet.',
    'changes.v12.installedTop': 'Com o Playbox na tela de início do iPhone, o topo da tela não fica mais borrado.',
    'changes.v13.molecules': 'Um jogo novinho! Ligue átomos para montar moléculas, da água ao benzeno. No modo fácil você vê o desenho; no difícil, só o nome.',
    'changes.v14.drive': 'Um jogo novinho! Dirija supercarros brilhantes por uma cidade neon, pela selva e por uma terra devastada com neve que vira deserto, e pegue todos os pontos. Nos níveis difíceis eles ficam nas beiradas e nas curvas.',
    'changes.v15.driveLooks': 'Turbo Drive agora parece jogo de console: texturas mais nítidas, sombras de verdade, neons e luzes que brilham, um céu com sol, nuvens e estrelas, carros brilhantes que refletem tudo, e fumaça, poeira, neve e faíscas nas rodas.',
    'changes.v16.fastUpdate': 'Depois de uma atualização, os jogos abrem na hora, sem esperar todos os jogos salvos baixarem. Jogos com arquivos novos também continuam salvos para usar offline.',
    'changes.v16.driveMusic': 'Cada pista tem sua própria música (com um botão para desligar), o motor ficou mais baixo e os botões mudaram: direção nas bordas, com freio e nitro no meio na tela em pé, ou ao lado da direção na tela deitada.',
    'changes.v17.steerYourself': 'Chega de direção automática: o carro só vira quando você vira, então ficar na pista depende de você.',
    'changes.v17.rotate': 'Ao girar o celular no app instalado, parte da tela não fica mais embaixo do entalhe, e na horizontal tudo fica longe dele.',
    'changes.v18.trackBuilder': 'Monte suas próprias pistas! Adicione retas e curvas, escolha a cidade, a selva ou a terra devastada e dirija nelas. O fim se liga sozinho ao começo, as pistas podem ser tão longas quanto você quiser e dá para compartilhar como arquivo ou código.',
    'changes.v18.barriers': 'As barreiras não viram mais o carro ao longo da pista: raspar numa deixa você bem devagar até você se afastar.',
    'changes.v19.boostPads': 'Chega de botões de nitro e freio: passe pelas setas azuis brilhantes na pista para um jato de nitro. É só virar!',
    'changes.v20.tilt': 'Vire inclinando o celular como um volante (escolha em Direção na garagem). Toque na tela para endireitar.',
    'changes.v20.customize': 'Personalize seu carro: pintura brilhante, fosca ou cromada, faixas de corrida, cor das rodas, aerofólio e luz de baixo colorida.',
    'changes.v21.autoUpdate': 'As atualizações agora chegam sozinhas: o app recarrega quando você volta para ele, ou na hora se você não estiver jogando, sem precisar fechar e abrir de novo.',
    'changes.v21.lighterStart': 'Primeira visita mais leve: estas novidades agora carregam só quando você as lê, ou em segundo plano no Wi-Fi.',
    'changes.v22.promise': 'Agora toda página diz claramente: sem anúncios, sem rastreamento, seus jogos e pontuações ficam neste aparelho, e o código é aberto no GitHub.',
    'changes.v23.looks': 'Novos visuais para os carros: cinco estilos de racha, adesivos laterais (ondas, tribal ou chamas), entrada de ar ou compressor no capô, pintura prata, limão e rosa choque, e luz de baixo azul.',
    'changes.v11.versionSpace': 'Mais espaço acima do número da versão no fim da página.',
    'changes.v10.iosTop': 'No iPhone nada mais desliza para baixo do relógio, então o topo da tela fica limpo.',
    'changes.v10.footer': 'Mais espaço no fim da página, para o número da versão não ficar escondido.',
    'changes.v10.firefox': 'Cantos arredondados na visão 3D no Firefox.',
    'changes.v9.iosBlur': 'No iPhone, a tela cheia não deixa mais o jogo deslizar para baixo da área borrada atrás do relógio.',
    'changes.v8.version': 'O fim de cada página mostra o número da versão, para você saber se tem a mais nova.',
    'changes.v7.focus': 'A tela cheia agora usa a tela toda: a barra de cima some e os botões dela vão para dentro do jogo.',
    'changes.v7.blocksPhones': 'Fica melhor no celular: uma paleta por vez, um botão pequeno para a hora do dia e as ferramentas de lado com o celular deitado.',
    'changes.v6.whatsNew': '“Novidades” mostra quais jogos foram adicionados ou atualizados.',
    'changes.v6.updateNotice': 'O Playbox avisa quando há uma atualização.',
    'changes.v5.languages': 'O Playbox agora fala inglês, italiano, espanhol, português do Brasil e alemão.',
    'changes.v4.memory': 'Um jogo novinho! Vire cartas com animais, planetas, bandeiras ou suas fotos.',
    'changes.v4.blocks': 'Um jogo novinho! Construa em 3D, do nascer do sol a uma noite estrelada.',
    'changes.v4.offline': 'Primeira visita mais rápida. Os jogos são salvos para usar offline quando você os abre.',
    'changes.v4.mageDice': 'Os dados da bruxa e do mago voltaram a ser 3D.',
    'changes.v3.looks': 'Cada amigo tem um segundo visual, com seu próprio cenário: Príncipe, Vaqueira, Aventureira e Menina Pixel.',
    'changes.v3.mage': 'Um amigo novo: a Bruxa, ou o Mago.',
    'changes.v2.music': 'Cada amigo tem sua própria música, com um botão para desligar.',
    'changes.v1.dice': 'O primeiro jogo, com quatro amigos que jogam os dados.',
  },
  de: {
    'changes.v6.fullscreen': 'Jedes Spiel hat einen Vollbild-Knopf, um den ganzen Bildschirm von Handy oder Tablet zu nutzen.',
    'changes.v12.installedTop': 'Wenn Playbox auf dem iPhone-Home-Bildschirm liegt, ist der obere Bildschirmrand nicht mehr verschwommen.',
    'changes.v13.molecules': 'Ein ganz neues Spiel! Verbinde Atome zu Molekülen, von Wasser bis Benzol. Im leichten Modus siehst du das Bild, im schweren nur den Namen.',
    'changes.v14.drive': 'Ein ganz neues Spiel! Fahr glänzende Supersportwagen durch eine Neonstadt, den Dschungel und ein verschneites Ödland, das zur Wüste wird, und sammle alle Punkte. In schweren Stufen liegen sie am Rand und in den Kurven.',
    'changes.v15.driveLooks': 'Turbo Drive sieht jetzt wie ein Konsolenspiel aus: schärfere Texturen, echte Schatten, leuchtende Neonlichter, ein Himmel mit Sonne, Wolken und Sternen, glänzende Autos, die ihn spiegeln, und Rauch, Staub, Schnee und Funken an den Rädern.',
    'changes.v16.fastUpdate': 'Nach einem Update öffnen sich Spiele wieder sofort, statt zu warten, bis alle gespeicherten Spiele geladen sind. Spiele mit neuen Dateien bleiben auch offline gespeichert.',
    'changes.v16.driveMusic': 'Jede Strecke hat ihre eigene Musik (mit einem Knopf zum Ausschalten), der Motor ist leiser, und die Tasten sind umgezogen: Lenken am Rand, Bremse und Nitro in der Mitte bei hohem Bildschirm, oder neben dem Lenken bei breitem.',
    'changes.v17.steerYourself': 'Kein automatisches Lenken mehr: Das Auto fährt nur Kurven, wenn du lenkst, also liegt es an dir, auf der Straße zu bleiben.',
    'changes.v17.rotate': 'Wenn du das Handy in der installierten App drehst, bleibt kein Teil mehr unter der Kerbe, und im Querformat bleibt alles frei davon.',
    'changes.v18.trackBuilder': 'Bau deine eigenen Strecken! Füg Geraden und Kurven hinzu, wähl Stadt, Dschungel oder Ödland und fahr los. Das Ende verbindet sich von selbst mit dem Start, Strecken können so lang sein, wie du willst, und du kannst sie als Datei oder Code teilen.',
    'changes.v18.barriers': 'Die Absperrungen lenken das Auto nicht mehr an der Straße entlang: Wer daran schrammt, wird ganz langsam, bis er weglenkt.',
    'changes.v19.boostPads': 'Keine Nitro- und Bremstasten mehr: Fahr über die leuchtenden blauen Pfeile auf der Straße für einen Nitro-Schub. Einfach lenken!',
    'changes.v20.tilt': 'Lenk, indem du das Handy wie ein Lenkrad neigst (unter Lenken in der Garage wählen). Tipp auf den Bildschirm zum Geradeausfahren.',
    'changes.v20.customize': 'Gestalte dein Auto: glänzender, matter oder Chrom-Lack, Rennstreifen, Felgenfarbe, Heckflügel und farbiges Unterbodenlicht.',
    'changes.v21.autoUpdate': 'Updates kommen jetzt von selbst: Die App lädt neu, wenn du zu ihr zurückkehrst, oder sofort, wenn du gerade nicht spielst, statt sie schließen und neu öffnen zu müssen.',
    'changes.v21.lighterStart': 'Leichterer erster Besuch: Diese Neuigkeiten laden jetzt erst, wenn du sie liest, oder im Hintergrund im WLAN.',
    'changes.v22.promise': 'Jetzt steht es auf jeder Seite: keine Werbung, kein Tracking, deine Spiele und Punkte bleiben auf diesem Gerät, und der Code ist Open Source auf GitHub.',
    'changes.v23.looks': 'Neue Auto-Looks: fünf Straßenrenner-Vorlagen, dazu Seitengrafiken (Schwünge, Tribal oder Flammen), Lufthutze oder Kompressor auf der Haube, Silber, Limette und Pink als Lack und blaues Unterbodenlicht.',
    'changes.v11.versionSpace': 'Mehr Platz über der Versionsnummer am Seitenende.',
    'changes.v10.iosTop': 'Auf dem iPhone rutscht nichts mehr unter die Uhr, der obere Rand bleibt sauber.',
    'changes.v10.footer': 'Mehr Platz am Seitenende, damit die Versionsnummer nicht verdeckt wird.',
    'changes.v10.firefox': 'Abgerundete Ecken der 3D-Ansicht in Firefox.',
    'changes.v9.iosBlur': 'Auf dem iPhone rutscht das Spiel im Vollbild nicht mehr unter den verschwommenen Bereich hinter der Uhr.',
    'changes.v8.version': 'Unten auf jeder Seite steht die Versionsnummer, damit du siehst, ob du die neueste hast.',
    'changes.v7.focus': 'Vollbild nutzt jetzt den ganzen Bildschirm: Die obere Leiste verschwindet und ihre Knöpfe wandern ins Spiel.',
    'changes.v7.blocksPhones': 'Passt besser aufs Handy: immer nur eine Palette, ein kleiner Knopf für die Tageszeit und die Werkzeuge an der Seite, wenn das Handy quer liegt.',
    'changes.v6.whatsNew': '„Neuigkeiten“ zeigt, welche Spiele neu sind oder aktualisiert wurden.',
    'changes.v6.updateNotice': 'Playbox sagt dir, wenn ein Update bereit ist.',
    'changes.v5.languages': 'Playbox spricht jetzt Englisch, Italienisch, Spanisch, brasilianisches Portugiesisch und Deutsch.',
    'changes.v4.memory': 'Ein ganz neues Spiel! Dreh Karten mit Tieren, Planeten, Flaggen oder deinen Fotos um.',
    'changes.v4.blocks': 'Ein ganz neues Spiel! Bau in 3D, vom Sonnenaufgang bis zur Sternennacht.',
    'changes.v4.offline': 'Schnellerer erster Besuch. Spiele werden fürs Offline-Spielen gespeichert, wenn du sie öffnest.',
    'changes.v4.mageDice': 'Die Würfel der Hexe und des Zauberers sind wieder 3D.',
    'changes.v3.looks': 'Jeder Freund hat ein zweites Aussehen mit eigener Kulisse: Prinz, Cowgirl, Abenteurerin und Pixel-Mädchen.',
    'changes.v3.mage': 'Ein neuer Freund: die Hexe oder der Zauberer.',
    'changes.v2.music': 'Jeder Freund hat seine eigene Musik, mit einem Knopf zum Ausschalten.',
    'changes.v1.dice': 'Das allererste Spiel, mit vier Freunden, die würfeln.',
  },
});
