// Memory texts: the interface, plus names and fun facts for every card.
// Card keys match themes.js. "Türkiye" is used in English; the other
// languages use their everyday name for the country.

import { addStrings } from '../../shared/i18n.js';

const ui = {
  en: {
    'memory.pageTitle': 'Memory · Playbox',
    'memory.setup': 'New game',
    'memory.pickCards': 'Pick your cards',
    'memory.photoHelp': 'Add your own pictures. They stay on this device only.',
    'memory.addPhotos': '+ Add photos',
    'memory.howBig': 'How big?',
    'memory.cardBack': 'Card back',
    'memory.deal': 'Deal the cards!',
    'memory.game': 'Game',
    'memory.pairs': 'Pairs',
    'memory.moves': 'Moves',
    'memory.time': 'Time',
    'memory.zoom': 'Zoom',
    'memory.fit': 'Fit',
    'memory.newGame': 'New game',
    'memory.winTitle': 'You found them all!',
    'memory.playAgain': 'Play again',
    'memory.changeCards': 'Change cards',
    'memory.theme.animals': 'Animals',
    'memory.theme.space': 'Space',
    'memory.theme.countries': 'Countries',
    'memory.theme.photos': 'My photos',
    'memory.back.classic': 'Classic',
    'memory.back.wood': 'Wood',
    'memory.back.galaxy': 'Galaxy',
    'memory.back.candy': 'Candy',
    'memory.pairsCount': { one: '{count} pair', other: '{count} pairs' },
    'memory.photoCount': { one: '{count} photo.', other: '{count} photos.' },
    'memory.addMore': 'Add {count} more to play.',
    'memory.enoughFor': 'Enough for {size}×{size}.',
    'memory.removePhoto': 'Remove photo',
    'memory.adding': 'Adding photos…',
    'memory.noRecord': 'No record yet for these cards. Can you set one?',
    'memory.best': 'Your best: {moves} moves in {time}.',
    'memory.freeCard': 'Free star card',
    'memory.faceDown': 'Card {number}, face down',
    'memory.findPairs': 'Find the pairs!',
    'memory.named': '{name}!',
    'memory.withFact': '{name}: {fact}',
    'memory.match': 'A match!',
    'memory.photoName': 'Photo {number}',
    'memory.newRecord': 'New record!',
    'memory.winDetail': '{moves} moves in {time}',
  },
  it: {
    'memory.pageTitle': 'Memory · Playbox',
    'memory.setup': 'Nuova partita',
    'memory.pickCards': 'Scegli le carte',
    'memory.photoHelp': 'Aggiungi le tue foto. Restano solo su questo dispositivo.',
    'memory.addPhotos': '+ Aggiungi foto',
    'memory.howBig': 'Quanto grande?',
    'memory.cardBack': 'Retro delle carte',
    'memory.deal': 'Distribuisci le carte!',
    'memory.game': 'Partita',
    'memory.pairs': 'Coppie',
    'memory.moves': 'Mosse',
    'memory.time': 'Tempo',
    'memory.zoom': 'Zoom',
    'memory.fit': 'Adatta',
    'memory.newGame': 'Nuova partita',
    'memory.winTitle': 'Le hai trovate tutte!',
    'memory.playAgain': 'Gioca ancora',
    'memory.changeCards': 'Cambia carte',
    'memory.theme.animals': 'Animali',
    'memory.theme.space': 'Spazio',
    'memory.theme.countries': 'Paesi',
    'memory.theme.photos': 'Le mie foto',
    'memory.back.classic': 'Classico',
    'memory.back.wood': 'Legno',
    'memory.back.galaxy': 'Galassia',
    'memory.back.candy': 'Caramella',
    'memory.pairsCount': { one: '{count} coppia', other: '{count} coppie' },
    'memory.photoCount': { one: '{count} foto.', other: '{count} foto.' },
    'memory.addMore': 'Aggiungine altre {count} per giocare.',
    'memory.enoughFor': 'Bastano per {size}×{size}.',
    'memory.removePhoto': 'Togli la foto',
    'memory.adding': 'Aggiungo le foto…',
    'memory.noRecord': 'Ancora nessun record con queste carte. Riesci a farne uno?',
    'memory.best': 'Il tuo record: {moves} mosse in {time}.',
    'memory.freeCard': 'Carta stella libera',
    'memory.faceDown': 'Carta {number}, coperta',
    'memory.findPairs': 'Trova le coppie!',
    'memory.named': '{name}!',
    'memory.withFact': '{name}: {fact}',
    'memory.match': 'Coppia trovata!',
    'memory.photoName': 'Foto {number}',
    'memory.newRecord': 'Nuovo record!',
    'memory.winDetail': '{moves} mosse in {time}',
  },
  es: {
    'memory.pageTitle': 'Memoria · Playbox',
    'memory.setup': 'Partida nueva',
    'memory.pickCards': 'Elige tus cartas',
    'memory.photoHelp': 'Añade tus propias fotos. Solo se quedan en este dispositivo.',
    'memory.addPhotos': '+ Añadir fotos',
    'memory.howBig': '¿De qué tamaño?',
    'memory.cardBack': 'Reverso de las cartas',
    'memory.deal': '¡Reparte las cartas!',
    'memory.game': 'Partida',
    'memory.pairs': 'Parejas',
    'memory.moves': 'Movimientos',
    'memory.time': 'Tiempo',
    'memory.zoom': 'Zoom',
    'memory.fit': 'Ajustar',
    'memory.newGame': 'Partida nueva',
    'memory.winTitle': '¡Las encontraste todas!',
    'memory.playAgain': 'Jugar otra vez',
    'memory.changeCards': 'Cambiar cartas',
    'memory.theme.animals': 'Animales',
    'memory.theme.space': 'Espacio',
    'memory.theme.countries': 'Países',
    'memory.theme.photos': 'Mis fotos',
    'memory.back.classic': 'Clásico',
    'memory.back.wood': 'Madera',
    'memory.back.galaxy': 'Galaxia',
    'memory.back.candy': 'Caramelo',
    'memory.pairsCount': { one: '{count} pareja', other: '{count} parejas' },
    'memory.photoCount': { one: '{count} foto.', other: '{count} fotos.' },
    'memory.addMore': 'Añade {count} más para jugar.',
    'memory.enoughFor': 'Suficientes para {size}×{size}.',
    'memory.removePhoto': 'Quitar foto',
    'memory.adding': 'Añadiendo fotos…',
    'memory.noRecord': 'Aún no hay récord con estas cartas. ¿Puedes lograr uno?',
    'memory.best': 'Tu récord: {moves} movimientos en {time}.',
    'memory.freeCard': 'Carta estrella libre',
    'memory.faceDown': 'Carta {number}, boca abajo',
    'memory.findPairs': '¡Encuentra las parejas!',
    'memory.named': '¡{name}!',
    'memory.withFact': '{name}: {fact}',
    'memory.match': '¡Pareja!',
    'memory.photoName': 'Foto {number}',
    'memory.newRecord': '¡Nuevo récord!',
    'memory.winDetail': '{moves} movimientos en {time}',
  },
  'pt-BR': {
    'memory.pageTitle': 'Jogo da Memória · Playbox',
    'memory.setup': 'Novo jogo',
    'memory.pickCards': 'Escolha suas cartas',
    'memory.photoHelp': 'Adicione suas próprias fotos. Elas ficam só neste aparelho.',
    'memory.addPhotos': '+ Adicionar fotos',
    'memory.howBig': 'De que tamanho?',
    'memory.cardBack': 'Verso das cartas',
    'memory.deal': 'Dar as cartas!',
    'memory.game': 'Jogo',
    'memory.pairs': 'Pares',
    'memory.moves': 'Jogadas',
    'memory.time': 'Tempo',
    'memory.zoom': 'Zoom',
    'memory.fit': 'Ajustar',
    'memory.newGame': 'Novo jogo',
    'memory.winTitle': 'Você achou todos!',
    'memory.playAgain': 'Jogar de novo',
    'memory.changeCards': 'Trocar cartas',
    'memory.theme.animals': 'Animais',
    'memory.theme.space': 'Espaço',
    'memory.theme.countries': 'Países',
    'memory.theme.photos': 'Minhas fotos',
    'memory.back.classic': 'Clássico',
    'memory.back.wood': 'Madeira',
    'memory.back.galaxy': 'Galáxia',
    'memory.back.candy': 'Doce',
    'memory.pairsCount': { one: '{count} par', other: '{count} pares' },
    'memory.photoCount': { one: '{count} foto.', other: '{count} fotos.' },
    'memory.addMore': 'Adicione mais {count} para jogar.',
    'memory.enoughFor': 'Dá para jogar {size}×{size}.',
    'memory.removePhoto': 'Tirar foto',
    'memory.adding': 'Adicionando fotos…',
    'memory.noRecord': 'Ainda não há recorde com estas cartas. Consegue fazer um?',
    'memory.best': 'Seu recorde: {moves} jogadas em {time}.',
    'memory.freeCard': 'Carta estrela livre',
    'memory.faceDown': 'Carta {number}, virada para baixo',
    'memory.findPairs': 'Encontre os pares!',
    'memory.named': '{name}!',
    'memory.withFact': '{name}: {fact}',
    'memory.match': 'Achou um par!',
    'memory.photoName': 'Foto {number}',
    'memory.newRecord': 'Novo recorde!',
    'memory.winDetail': '{moves} jogadas em {time}',
  },
  de: {
    'memory.pageTitle': 'Memo-Spiel · Playbox',
    'memory.setup': 'Neues Spiel',
    'memory.pickCards': 'Wähle deine Karten',
    'memory.photoHelp': 'Füge eigene Fotos hinzu. Sie bleiben nur auf diesem Gerät.',
    'memory.addPhotos': '+ Fotos hinzufügen',
    'memory.howBig': 'Wie groß?',
    'memory.cardBack': 'Kartenrückseite',
    'memory.deal': 'Karten austeilen!',
    'memory.game': 'Spiel',
    'memory.pairs': 'Paare',
    'memory.moves': 'Züge',
    'memory.time': 'Zeit',
    'memory.zoom': 'Zoom',
    'memory.fit': 'Anpassen',
    'memory.newGame': 'Neues Spiel',
    'memory.winTitle': 'Du hast alle gefunden!',
    'memory.playAgain': 'Nochmal spielen',
    'memory.changeCards': 'Karten wechseln',
    'memory.theme.animals': 'Tiere',
    'memory.theme.space': 'Weltall',
    'memory.theme.countries': 'Länder',
    'memory.theme.photos': 'Meine Fotos',
    'memory.back.classic': 'Klassisch',
    'memory.back.wood': 'Holz',
    'memory.back.galaxy': 'Galaxie',
    'memory.back.candy': 'Bonbon',
    'memory.pairsCount': { one: '{count} Paar', other: '{count} Paare' },
    'memory.photoCount': { one: '{count} Foto.', other: '{count} Fotos.' },
    'memory.addMore': 'Füge noch {count} hinzu, um zu spielen.',
    'memory.enoughFor': 'Reicht für {size}×{size}.',
    'memory.removePhoto': 'Foto entfernen',
    'memory.adding': 'Fotos werden hinzugefügt…',
    'memory.noRecord': 'Noch kein Rekord mit diesen Karten. Schaffst du einen?',
    'memory.best': 'Dein Rekord: {moves} Züge in {time}.',
    'memory.freeCard': 'Freie Sternkarte',
    'memory.faceDown': 'Karte {number}, verdeckt',
    'memory.findPairs': 'Finde die Paare!',
    'memory.named': '{name}!',
    'memory.withFact': '{name}: {fact}',
    'memory.match': 'Ein Paar!',
    'memory.photoName': 'Foto {number}',
    'memory.newRecord': 'Neuer Rekord!',
    'memory.winDetail': '{moves} Züge in {time}',
  },
};

// Animals: [key, en, it, es, pt-BR, de]
const ANIMALS = [
  ['lion', 'Lion', 'Leone', 'León', 'Leão', 'Löwe'],
  ['elephant', 'Elephant', 'Elefante', 'Elefante', 'Elefante', 'Elefant'],
  ['giraffe', 'Giraffe', 'Giraffa', 'Jirafa', 'Girafa', 'Giraffe'],
  ['zebra', 'Zebra', 'Zebra', 'Cebra', 'Zebra', 'Zebra'],
  ['panda', 'Panda', 'Panda', 'Panda', 'Panda', 'Panda'],
  ['koala', 'Koala', 'Koala', 'Koala', 'Coala', 'Koala'],
  ['kangaroo', 'Kangaroo', 'Canguro', 'Canguro', 'Canguru', 'Känguru'],
  ['tiger', 'Tiger', 'Tigre', 'Tigre', 'Tigre', 'Tiger'],
  ['monkey', 'Monkey', 'Scimmia', 'Mono', 'Macaco', 'Affe'],
  ['penguin', 'Penguin', 'Pinguino', 'Pingüino', 'Pinguim', 'Pinguin'],
  ['polar-bear', 'Polar bear', 'Orso polare', 'Oso polar', 'Urso-polar', 'Eisbär'],
  ['fox', 'Fox', 'Volpe', 'Zorro', 'Raposa', 'Fuchs'],
  ['owl', 'Owl', 'Gufo', 'Búho', 'Coruja', 'Eule'],
  ['rabbit', 'Rabbit', 'Coniglio', 'Conejo', 'Coelho', 'Kaninchen'],
  ['hedgehog', 'Hedgehog', 'Riccio', 'Erizo', 'Ouriço', 'Igel'],
  ['squirrel', 'Squirrel', 'Scoiattolo', 'Ardilla', 'Esquilo', 'Eichhörnchen'],
  ['deer', 'Deer', 'Cerbiatto', 'Ciervo', 'Veado', 'Reh'],
  ['raccoon', 'Raccoon', 'Procione', 'Mapache', 'Guaxinim', 'Waschbär'],
  ['dolphin', 'Dolphin', 'Delfino', 'Delfín', 'Golfinho', 'Delfin'],
  ['whale', 'Whale', 'Balena', 'Ballena', 'Baleia', 'Wal'],
  ['octopus', 'Octopus', 'Polpo', 'Pulpo', 'Polvo', 'Krake'],
  ['sea-turtle', 'Sea turtle', 'Tartaruga marina', 'Tortuga marina', 'Tartaruga-marinha', 'Meeresschildkröte'],
  ['crab', 'Crab', 'Granchio', 'Cangrejo', 'Caranguejo', 'Krabbe'],
  ['flamingo', 'Flamingo', 'Fenicottero', 'Flamenco', 'Flamingo', 'Flamingo'],
  ['parrot', 'Parrot', 'Pappagallo', 'Loro', 'Papagaio', 'Papagei'],
  ['frog', 'Frog', 'Rana', 'Rana', 'Sapo', 'Frosch'],
  ['butterfly', 'Butterfly', 'Farfalla', 'Mariposa', 'Borboleta', 'Schmetterling'],
];

// Space: key → { language: [name, fact] }
const SPACE = {
  sun: {
    en: ['The Sun', 'The Sun is a star. About 1.3 million Earths could fit inside it.'],
    it: ['Il Sole', 'Il Sole è una stella. Dentro potrebbero starci circa 1,3 milioni di Terre.'],
    es: ['El Sol', 'El Sol es una estrella. Dentro cabrían unos 1,3 millones de Tierras.'],
    'pt-BR': ['O Sol', 'O Sol é uma estrela. Dentro dele caberiam cerca de 1,3 milhão de Terras.'],
    de: ['Die Sonne', 'Die Sonne ist ein Stern. Etwa 1,3 Millionen Erden würden in sie hineinpassen.'],
  },
  mercury: {
    en: ['Mercury', 'Mercury is the smallest planet and the closest one to the Sun.'],
    it: ['Mercurio', 'Mercurio è il pianeta più piccolo e il più vicino al Sole.'],
    es: ['Mercurio', 'Mercurio es el planeta más pequeño y el más cercano al Sol.'],
    'pt-BR': ['Mercúrio', 'Mercúrio é o menor planeta e o mais perto do Sol.'],
    de: ['Merkur', 'Merkur ist der kleinste Planet und der Sonne am nächsten.'],
  },
  venus: {
    en: ['Venus', 'Venus is the hottest planet, even hotter than Mercury.'],
    it: ['Venere', 'Venere è il pianeta più caldo, ancora più di Mercurio.'],
    es: ['Venus', 'Venus es el planeta más caliente, aún más que Mercurio.'],
    'pt-BR': ['Vênus', 'Vênus é o planeta mais quente, mais até do que Mercúrio.'],
    de: ['Venus', 'Die Venus ist der heißeste Planet, sogar heißer als Merkur.'],
  },
  earth: {
    en: ['Earth', 'Earth is the only planet we know of that has life.'],
    it: ['Terra', 'La Terra è l’unico pianeta che conosciamo dove c’è la vita.'],
    es: ['Tierra', 'La Tierra es el único planeta que conocemos con vida.'],
    'pt-BR': ['Terra', 'A Terra é o único planeta que conhecemos que tem vida.'],
    de: ['Erde', 'Die Erde ist der einzige Planet, von dem wir wissen, dass es dort Leben gibt.'],
  },
  moon: {
    en: ['The Moon', 'People first walked on the Moon in 1969.'],
    it: ['La Luna', 'Le persone hanno camminato sulla Luna per la prima volta nel 1969.'],
    es: ['La Luna', 'Las personas caminaron por primera vez sobre la Luna en 1969.'],
    'pt-BR': ['A Lua', 'As pessoas andaram na Lua pela primeira vez em 1969.'],
    de: ['Der Mond', '1969 sind zum ersten Mal Menschen auf dem Mond gelaufen.'],
  },
  mars: {
    en: ['Mars', 'Mars looks red because of rusty iron in its dust.'],
    it: ['Marte', 'Marte sembra rosso per il ferro arrugginito nella sua polvere.'],
    es: ['Marte', 'Marte se ve rojo por el hierro oxidado de su polvo.'],
    'pt-BR': ['Marte', 'Marte parece vermelho por causa do ferro enferrujado na sua poeira.'],
    de: ['Mars', 'Der Mars sieht rot aus, weil sein Staub rostiges Eisen enthält.'],
  },
  phobos: {
    en: ['Phobos', 'Phobos, a moon of Mars, goes around Mars about three times a day.'],
    it: ['Fobos', 'Fobos, una luna di Marte, gira intorno a Marte circa tre volte al giorno.'],
    es: ['Fobos', 'Fobos, una luna de Marte, da la vuelta a Marte unas tres veces al día.'],
    'pt-BR': ['Fobos', 'Fobos, uma lua de Marte, dá a volta em Marte cerca de três vezes por dia.'],
    de: ['Phobos', 'Phobos, ein Mond des Mars, umkreist den Mars etwa dreimal am Tag.'],
  },
  deimos: {
    en: ['Deimos', 'Deimos is the smaller moon of Mars, only about 12 km across.'],
    it: ['Deimos', 'Deimos è la luna più piccola di Marte: è larga solo circa 12 km.'],
    es: ['Deimos', 'Deimos es la luna más pequeña de Marte: mide solo unos 12 km.'],
    'pt-BR': ['Deimos', 'Deimos é a lua menor de Marte: tem só cerca de 12 km.'],
    de: ['Deimos', 'Deimos ist der kleinere Mond des Mars, nur etwa 12 km groß.'],
  },
  ceres: {
    en: ['Ceres', 'Ceres is a dwarf planet in the asteroid belt between Mars and Jupiter.'],
    it: ['Cerere', 'Cerere è un pianeta nano nella fascia degli asteroidi, tra Marte e Giove.'],
    es: ['Ceres', 'Ceres es un planeta enano del cinturón de asteroides, entre Marte y Júpiter.'],
    'pt-BR': ['Ceres', 'Ceres é um planeta anão no cinturão de asteroides, entre Marte e Júpiter.'],
    de: ['Ceres', 'Ceres ist ein Zwergplanet im Asteroidengürtel zwischen Mars und Jupiter.'],
  },
  jupiter: {
    en: ['Jupiter', 'Jupiter is the biggest planet. Its Great Red Spot is a storm bigger than Earth.'],
    it: ['Giove', 'Giove è il pianeta più grande. La sua Grande Macchia Rossa è una tempesta più grande della Terra.'],
    es: ['Júpiter', 'Júpiter es el planeta más grande. Su Gran Mancha Roja es una tormenta más grande que la Tierra.'],
    'pt-BR': ['Júpiter', 'Júpiter é o maior planeta. Sua Grande Mancha Vermelha é uma tempestade maior que a Terra.'],
    de: ['Jupiter', 'Jupiter ist der größte Planet. Sein Großer Roter Fleck ist ein Sturm, der größer ist als die Erde.'],
  },
  io: {
    en: ['Io', 'Io, a moon of Jupiter, has hundreds of active volcanoes.'],
    it: ['Io', 'Io, una luna di Giove, ha centinaia di vulcani attivi.'],
    es: ['Ío', 'Ío, una luna de Júpiter, tiene cientos de volcanes activos.'],
    'pt-BR': ['Io', 'Io, uma lua de Júpiter, tem centenas de vulcões ativos.'],
    de: ['Io', 'Io, ein Mond des Jupiter, hat Hunderte aktive Vulkane.'],
  },
  europa: {
    en: ['Europa', 'Europa, a moon of Jupiter, has a salty ocean hidden under its ice.'],
    it: ['Europa', 'Europa, una luna di Giove, ha un oceano salato nascosto sotto il ghiaccio.'],
    es: ['Europa', 'Europa, una luna de Júpiter, tiene un océano salado escondido bajo el hielo.'],
    'pt-BR': ['Europa', 'Europa, uma lua de Júpiter, tem um oceano salgado escondido sob o gelo.'],
    de: ['Europa', 'Europa, ein Mond des Jupiter, hat unter seinem Eis einen salzigen Ozean.'],
  },
  ganymede: {
    en: ['Ganymede', 'Ganymede, a moon of Jupiter, is the biggest moon in the solar system.'],
    it: ['Ganimede', 'Ganimede, una luna di Giove, è la luna più grande del sistema solare.'],
    es: ['Ganímedes', 'Ganímedes, una luna de Júpiter, es la luna más grande del sistema solar.'],
    'pt-BR': ['Ganimedes', 'Ganimedes, uma lua de Júpiter, é a maior lua do Sistema Solar.'],
    de: ['Ganymed', 'Ganymed, ein Mond des Jupiter, ist der größte Mond im Sonnensystem.'],
  },
  callisto: {
    en: ['Callisto', 'Callisto, a moon of Jupiter, is covered in craters.'],
    it: ['Callisto', 'Callisto, una luna di Giove, è coperta di crateri.'],
    es: ['Calisto', 'Calisto, una luna de Júpiter, está cubierta de cráteres.'],
    'pt-BR': ['Calisto', 'Calisto, uma lua de Júpiter, é coberta de crateras.'],
    de: ['Kallisto', 'Kallisto, ein Mond des Jupiter, ist voller Krater.'],
  },
  saturn: {
    en: ['Saturn', 'Saturn’s rings are made of chunks of ice and rock.'],
    it: ['Saturno', 'Gli anelli di Saturno sono fatti di pezzi di ghiaccio e roccia.'],
    es: ['Saturno', 'Los anillos de Saturno están hechos de trozos de hielo y roca.'],
    'pt-BR': ['Saturno', 'Os anéis de Saturno são feitos de pedaços de gelo e rocha.'],
    de: ['Saturn', 'Die Ringe des Saturn bestehen aus Brocken aus Eis und Gestein.'],
  },
  titan: {
    en: ['Titan', 'Titan, a moon of Saturn, has lakes of liquid methane.'],
    it: ['Titano', 'Titano, una luna di Saturno, ha laghi di metano liquido.'],
    es: ['Titán', 'Titán, una luna de Saturno, tiene lagos de metano líquido.'],
    'pt-BR': ['Titã', 'Titã, uma lua de Saturno, tem lagos de metano líquido.'],
    de: ['Titan', 'Titan, ein Mond des Saturn, hat Seen aus flüssigem Methan.'],
  },
  enceladus: {
    en: ['Enceladus', 'Enceladus, a moon of Saturn, shoots jets of water into space.'],
    it: ['Encelado', 'Encelado, una luna di Saturno, spara getti d’acqua nello spazio.'],
    es: ['Encélado', 'Encélado, una luna de Saturno, lanza chorros de agua al espacio.'],
    'pt-BR': ['Encélado', 'Encélado, uma lua de Saturno, lança jatos de água no espaço.'],
    de: ['Enceladus', 'Enceladus, ein Mond des Saturn, schießt Wasserfontänen ins All.'],
  },
  mimas: {
    en: ['Mimas', 'Mimas, a moon of Saturn, has one giant crater called Herschel.'],
    it: ['Mimas', 'Mimas, una luna di Saturno, ha un cratere enorme chiamato Herschel.'],
    es: ['Mimas', 'Mimas, una luna de Saturno, tiene un cráter gigante llamado Herschel.'],
    'pt-BR': ['Mimas', 'Mimas, uma lua de Saturno, tem uma cratera gigante chamada Herschel.'],
    de: ['Mimas', 'Mimas, ein Mond des Saturn, hat einen riesigen Krater namens Herschel.'],
  },
  rhea: {
    en: ['Rhea', 'Rhea is the second-biggest moon of Saturn.'],
    it: ['Rea', 'Rea è la seconda luna più grande di Saturno.'],
    es: ['Rea', 'Rea es la segunda luna más grande de Saturno.'],
    'pt-BR': ['Reia', 'Reia é a segunda maior lua de Saturno.'],
    de: ['Rhea', 'Rhea ist der zweitgrößte Mond des Saturn.'],
  },
  iapetus: {
    en: ['Iapetus', 'Iapetus, a moon of Saturn, is dark on one side and bright on the other.'],
    it: ['Giapeto', 'Giapeto, una luna di Saturno, è scuro da un lato e chiaro dall’altro.'],
    es: ['Jápeto', 'Jápeto, una luna de Saturno, es oscuro por un lado y claro por el otro.'],
    'pt-BR': ['Jápeto', 'Jápeto, uma lua de Saturno, é escuro de um lado e claro do outro.'],
    de: ['Iapetus', 'Iapetus, ein Mond des Saturn, ist auf einer Seite dunkel und auf der anderen hell.'],
  },
  uranus: {
    en: ['Uranus', 'Uranus spins on its side, like a rolling ball.'],
    it: ['Urano', 'Urano gira su un fianco, come una palla che rotola.'],
    es: ['Urano', 'Urano gira de lado, como una pelota que rueda.'],
    'pt-BR': ['Urano', 'Urano gira deitado, como uma bola rolando.'],
    de: ['Uranus', 'Uranus dreht sich auf der Seite liegend, wie eine rollende Kugel.'],
  },
  miranda: {
    en: ['Miranda', 'Miranda, a moon of Uranus, has cliffs about 20 km high.'],
    it: ['Miranda', 'Miranda, una luna di Urano, ha scogliere alte circa 20 km.'],
    es: ['Miranda', 'Miranda, una luna de Urano, tiene acantilados de unos 20 km de altura.'],
    'pt-BR': ['Miranda', 'Miranda, uma lua de Urano, tem penhascos de cerca de 20 km de altura.'],
    de: ['Miranda', 'Miranda, ein Mond des Uranus, hat Klippen, die etwa 20 km hoch sind.'],
  },
  titania: {
    en: ['Titania', 'Titania is the biggest moon of Uranus.'],
    it: ['Titania', 'Titania è la luna più grande di Urano.'],
    es: ['Titania', 'Titania es la luna más grande de Urano.'],
    'pt-BR': ['Titânia', 'Titânia é a maior lua de Urano.'],
    de: ['Titania', 'Titania ist der größte Mond des Uranus.'],
  },
  neptune: {
    en: ['Neptune', 'Neptune has the fastest winds in the solar system.'],
    it: ['Nettuno', 'Nettuno ha i venti più veloci del sistema solare.'],
    es: ['Neptuno', 'Neptuno tiene los vientos más rápidos del sistema solar.'],
    'pt-BR': ['Netuno', 'Netuno tem os ventos mais rápidos do Sistema Solar.'],
    de: ['Neptun', 'Neptun hat die schnellsten Winde im Sonnensystem.'],
  },
  triton: {
    en: ['Triton', 'Triton, the biggest moon of Neptune, goes around it backwards.'],
    it: ['Tritone', 'Tritone, la luna più grande di Nettuno, gli gira intorno al contrario.'],
    es: ['Tritón', 'Tritón, la luna más grande de Neptuno, gira a su alrededor al revés.'],
    'pt-BR': ['Tritão', 'Tritão, a maior lua de Netuno, gira em volta dele ao contrário.'],
    de: ['Triton', 'Triton, der größte Mond des Neptun, umkreist ihn rückwärts.'],
  },
  pluto: {
    en: ['Pluto', 'Pluto is a dwarf planet with a big heart-shaped plain of ice.'],
    it: ['Plutone', 'Plutone è un pianeta nano con una grande pianura di ghiaccio a forma di cuore.'],
    es: ['Plutón', 'Plutón es un planeta enano con una gran llanura de hielo en forma de corazón.'],
    'pt-BR': ['Plutão', 'Plutão é um planeta anão com uma grande planície de gelo em forma de coração.'],
    de: ['Pluto', 'Pluto ist ein Zwergplanet mit einer großen, herzförmigen Eisebene.'],
  },
  charon: {
    en: ['Charon', 'Charon, the biggest moon of Pluto, is about half as wide as Pluto.'],
    it: ['Caronte', 'Caronte, la luna più grande di Plutone, è larga circa la metà di Plutone.'],
    es: ['Caronte', 'Caronte, la luna más grande de Plutón, mide casi la mitad que Plutón.'],
    'pt-BR': ['Caronte', 'Caronte, a maior lua de Plutão, tem cerca da metade da largura de Plutão.'],
    de: ['Charon', 'Charon, der größte Mond des Pluto, ist etwa halb so breit wie Pluto.'],
  },
};

// Countries: key → { language: [name, fact] }
const COUNTRIES = {
  japan: {
    en: ['Japan', 'Japan is made of thousands of islands. Mount Fuji is its tallest mountain.'],
    it: ['Giappone', 'Il Giappone è fatto di migliaia di isole. Il monte Fuji è la sua montagna più alta.'],
    es: ['Japón', 'Japón está formado por miles de islas. El monte Fuji es su montaña más alta.'],
    'pt-BR': ['Japão', 'O Japão é formado por milhares de ilhas. O monte Fuji é sua montanha mais alta.'],
    de: ['Japan', 'Japan besteht aus Tausenden Inseln. Der Fuji ist sein höchster Berg.'],
  },
  france: {
    en: ['France', 'The Eiffel Tower in Paris was built in 1889.'],
    it: ['Francia', 'La Torre Eiffel di Parigi è stata costruita nel 1889.'],
    es: ['Francia', 'La Torre Eiffel de París se construyó en 1889.'],
    'pt-BR': ['França', 'A Torre Eiffel, em Paris, foi construída em 1889.'],
    de: ['Frankreich', 'Der Eiffelturm in Paris wurde 1889 gebaut.'],
  },
  italy: {
    en: ['Italy', 'Pizza as we know it comes from Naples, a city in Italy.'],
    it: ['Italia', 'La pizza come la conosciamo viene da Napoli.'],
    es: ['Italia', 'La pizza tal como la conocemos viene de Nápoles, una ciudad de Italia.'],
    'pt-BR': ['Itália', 'A pizza como conhecemos vem de Nápoles, uma cidade da Itália.'],
    de: ['Italien', 'Die Pizza, wie wir sie kennen, kommt aus Neapel, einer Stadt in Italien.'],
  },
  germany: {
    en: ['Germany', 'Germany is famous for its forests, like the Black Forest.'],
    it: ['Germania', 'La Germania è famosa per i suoi boschi, come la Foresta Nera.'],
    es: ['Alemania', 'Alemania es famosa por sus bosques, como la Selva Negra.'],
    'pt-BR': ['Alemanha', 'A Alemanha é famosa por suas florestas, como a Floresta Negra.'],
    de: ['Deutschland', 'Deutschland ist berühmt für seine Wälder, wie den Schwarzwald.'],
  },
  ireland: {
    en: ['Ireland', 'Ireland is called the Emerald Isle because it is so green.'],
    it: ['Irlanda', 'L’Irlanda è chiamata l’Isola di Smeraldo perché è verdissima.'],
    es: ['Irlanda', 'A Irlanda la llaman la Isla Esmeralda porque es muy verde.'],
    'pt-BR': ['Irlanda', 'A Irlanda é chamada de Ilha Esmeralda porque é muito verde.'],
    de: ['Irland', 'Irland nennt man die Grüne Insel, weil es dort so grün ist.'],
  },
  belgium: {
    en: ['Belgium', 'Belgium is famous for its chocolate and waffles.'],
    it: ['Belgio', 'Il Belgio è famoso per il cioccolato e i waffle.'],
    es: ['Bélgica', 'Bélgica es famosa por su chocolate y sus gofres.'],
    'pt-BR': ['Bélgica', 'A Bélgica é famosa pelo chocolate e pelos waffles.'],
    de: ['Belgien', 'Belgien ist berühmt für Schokolade und Waffeln.'],
  },
  netherlands: {
    en: ['Netherlands', 'The Netherlands has more bicycles than people.'],
    it: ['Paesi Bassi', 'Nei Paesi Bassi ci sono più biciclette che persone.'],
    es: ['Países Bajos', 'En los Países Bajos hay más bicicletas que personas.'],
    'pt-BR': ['Países Baixos', 'Nos Países Baixos há mais bicicletas do que pessoas.'],
    de: ['Niederlande', 'In den Niederlanden gibt es mehr Fahrräder als Menschen.'],
  },
  austria: {
    en: ['Austria', 'Mozart, a famous composer, was born in Salzburg, Austria.'],
    it: ['Austria', 'Mozart, un famoso compositore, è nato a Salisburgo, in Austria.'],
    es: ['Austria', 'Mozart, un compositor famoso, nació en Salzburgo, Austria.'],
    'pt-BR': ['Áustria', 'Mozart, um compositor famoso, nasceu em Salzburgo, na Áustria.'],
    de: ['Österreich', 'Mozart, ein berühmter Komponist, wurde in Salzburg in Österreich geboren.'],
  },
  poland: {
    en: ['Poland', 'Marie Curie, who won two Nobel Prizes, was born in Warsaw, Poland.'],
    it: ['Polonia', 'Marie Curie, che vinse due premi Nobel, è nata a Varsavia, in Polonia.'],
    es: ['Polonia', 'Marie Curie, que ganó dos premios Nobel, nació en Varsovia, Polonia.'],
    'pt-BR': ['Polônia', 'Marie Curie, que ganhou dois prêmios Nobel, nasceu em Varsóvia, na Polônia.'],
    de: ['Polen', 'Marie Curie, die zwei Nobelpreise gewann, wurde in Warschau in Polen geboren.'],
  },
  ukraine: {
    en: ['Ukraine', 'Ukraine grows huge fields of sunflowers.'],
    it: ['Ucraina', 'In Ucraina ci sono enormi campi di girasoli.'],
    es: ['Ucrania', 'Ucrania cultiva enormes campos de girasoles.'],
    'pt-BR': ['Ucrânia', 'A Ucrânia cultiva enormes campos de girassóis.'],
    de: ['Ukraine', 'In der Ukraine wachsen riesige Sonnenblumenfelder.'],
  },
  sweden: {
    en: ['Sweden', 'Sweden has a hotel made of ice that is built again every winter.'],
    it: ['Svezia', 'In Svezia c’è un hotel di ghiaccio che viene ricostruito ogni inverno.'],
    es: ['Suecia', 'Suecia tiene un hotel de hielo que se vuelve a construir cada invierno.'],
    'pt-BR': ['Suécia', 'A Suécia tem um hotel de gelo que é construído de novo todo inverno.'],
    de: ['Schweden', 'In Schweden gibt es ein Hotel aus Eis, das jeden Winter neu gebaut wird.'],
  },
  norway: {
    en: ['Norway', 'In the north of Norway, the sun does not set for weeks in summer.'],
    it: ['Norvegia', 'Nel nord della Norvegia, d’estate il sole non tramonta per settimane.'],
    es: ['Noruega', 'En el norte de Noruega, en verano el sol no se pone durante semanas.'],
    'pt-BR': ['Noruega', 'No norte da Noruega, no verão o sol não se põe por semanas.'],
    de: ['Norwegen', 'Im Norden Norwegens geht die Sonne im Sommer wochenlang nicht unter.'],
  },
  denmark: {
    en: ['Denmark', 'LEGO toy bricks were invented in Denmark.'],
    it: ['Danimarca', 'I mattoncini LEGO sono stati inventati in Danimarca.'],
    es: ['Dinamarca', 'Los bloques de juguete LEGO se inventaron en Dinamarca.'],
    'pt-BR': ['Dinamarca', 'Os blocos de brinquedo LEGO foram inventados na Dinamarca.'],
    de: ['Dänemark', 'Die LEGO-Steine wurden in Dänemark erfunden.'],
  },
  finland: {
    en: ['Finland', 'Finland has about 188,000 lakes.'],
    it: ['Finlandia', 'La Finlandia ha circa 188.000 laghi.'],
    es: ['Finlandia', 'Finlandia tiene unos 188.000 lagos.'],
    'pt-BR': ['Finlândia', 'A Finlândia tem cerca de 188 mil lagos.'],
    de: ['Finnland', 'Finnland hat etwa 188.000 Seen.'],
  },
  switzerland: {
    en: ['Switzerland', 'Switzerland has four official languages.'],
    it: ['Svizzera', 'La Svizzera ha quattro lingue nazionali.'],
    es: ['Suiza', 'Suiza tiene cuatro idiomas nacionales.'],
    'pt-BR': ['Suíça', 'A Suíça tem quatro idiomas nacionais.'],
    de: ['Schweiz', 'Die Schweiz hat vier Landessprachen.'],
  },
  greece: {
    en: ['Greece', 'The first Olympic Games were held in ancient Greece.'],
    it: ['Grecia', 'I primi Giochi Olimpici si sono svolti nell’antica Grecia.'],
    es: ['Grecia', 'Los primeros Juegos Olímpicos se celebraron en la antigua Grecia.'],
    'pt-BR': ['Grécia', 'Os primeiros Jogos Olímpicos aconteceram na Grécia antiga.'],
    de: ['Griechenland', 'Die ersten Olympischen Spiele fanden im alten Griechenland statt.'],
  },
  bangladesh: {
    en: ['Bangladesh', 'Bengal tigers live in the Sundarbans, a mangrove forest in Bangladesh.'],
    it: ['Bangladesh', 'Le tigri del Bengala vivono nelle Sundarbans, una foresta di mangrovie del Bangladesh.'],
    es: ['Bangladés', 'Los tigres de Bengala viven en los Sundarbans, un bosque de manglares de Bangladés.'],
    'pt-BR': ['Bangladesh', 'Os tigres-de-bengala vivem nos Sundarbans, uma floresta de mangue em Bangladesh.'],
    de: ['Bangladesch', 'Bengalische Tiger leben in den Sundarbans, einem Mangrovenwald in Bangladesch.'],
  },
  nigeria: {
    en: ['Nigeria', 'Nigeria has more people than any other country in Africa.'],
    it: ['Nigeria', 'La Nigeria ha più abitanti di qualsiasi altro paese dell’Africa.'],
    es: ['Nigeria', 'Nigeria tiene más habitantes que cualquier otro país de África.'],
    'pt-BR': ['Nigéria', 'A Nigéria tem mais habitantes do que qualquer outro país da África.'],
    de: ['Nigeria', 'Nigeria hat mehr Einwohner als jedes andere Land in Afrika.'],
  },
  colombia: {
    en: ['Colombia', 'Colombia has more kinds of birds than almost any other country.'],
    it: ['Colombia', 'La Colombia ha più specie di uccelli di quasi ogni altro paese.'],
    es: ['Colombia', 'Colombia tiene más especies de aves que casi cualquier otro país.'],
    'pt-BR': ['Colômbia', 'A Colômbia tem mais espécies de aves do que quase qualquer outro país.'],
    de: ['Kolumbien', 'Kolumbien hat mehr Vogelarten als fast jedes andere Land.'],
  },
  indonesia: {
    en: ['Indonesia', 'Indonesia is made of more than 17,000 islands.'],
    it: ['Indonesia', 'L’Indonesia è fatta di più di 17.000 isole.'],
    es: ['Indonesia', 'Indonesia está formada por más de 17.000 islas.'],
    'pt-BR': ['Indonésia', 'A Indonésia é formada por mais de 17 mil ilhas.'],
    de: ['Indonesien', 'Indonesien besteht aus mehr als 17.000 Inseln.'],
  },
  thailand: {
    en: ['Thailand', 'The full name of Bangkok, Thailand’s capital, is one of the longest city names in the world.'],
    it: ['Thailandia', 'Il nome completo di Bangkok, la capitale della Thailandia, è uno dei nomi di città più lunghi del mondo.'],
    es: ['Tailandia', 'El nombre completo de Bangkok, la capital de Tailandia, es uno de los nombres de ciudad más largos del mundo.'],
    'pt-BR': ['Tailândia', 'O nome completo de Bangkok, a capital da Tailândia, é um dos nomes de cidade mais longos do mundo.'],
    de: ['Thailand', 'Der volle Name von Bangkok, der Hauptstadt Thailands, ist einer der längsten Städtenamen der Welt.'],
  },
  estonia: {
    en: ['Estonia', 'About half of Estonia is covered by forest.'],
    it: ['Estonia', 'Circa metà dell’Estonia è coperta da boschi.'],
    es: ['Estonia', 'Casi la mitad de Estonia está cubierta de bosques.'],
    'pt-BR': ['Estônia', 'Cerca de metade da Estônia é coberta por florestas.'],
    de: ['Estland', 'Etwa die Hälfte von Estland ist mit Wald bedeckt.'],
  },
  hungary: {
    en: ['Hungary', 'The Rubik’s Cube was invented in Hungary.'],
    it: ['Ungheria', 'Il cubo di Rubik è stato inventato in Ungheria.'],
    es: ['Hungría', 'El cubo de Rubik se inventó en Hungría.'],
    'pt-BR': ['Hungria', 'O cubo mágico foi inventado na Hungria.'],
    de: ['Ungarn', 'Der Zauberwürfel wurde in Ungarn erfunden.'],
  },
  lithuania: {
    en: ['Lithuania', 'Lithuania has a Hill of Crosses with more than 100,000 crosses.'],
    it: ['Lituania', 'In Lituania c’è la Collina delle Croci, con più di 100.000 croci.'],
    es: ['Lituania', 'Lituania tiene una Colina de las Cruces con más de 100.000 cruces.'],
    'pt-BR': ['Lituânia', 'A Lituânia tem um Morro das Cruzes com mais de 100 mil cruzes.'],
    de: ['Litauen', 'In Litauen gibt es einen Berg der Kreuze mit mehr als 100.000 Kreuzen.'],
  },
  chile: {
    en: ['Chile', 'Chile is very long and thin: more than 4,000 km from north to south.'],
    it: ['Cile', 'Il Cile è lunghissimo e stretto: più di 4.000 km da nord a sud.'],
    es: ['Chile', 'Chile es muy largo y estrecho: más de 4.000 km de norte a sur.'],
    'pt-BR': ['Chile', 'O Chile é bem comprido e estreito: mais de 4 mil km de norte a sul.'],
    de: ['Chile', 'Chile ist sehr lang und schmal: mehr als 4.000 km von Norden nach Süden.'],
  },
  vietnam: {
    en: ['Vietnam', 'Vietnam has Son Doong, one of the biggest caves in the world.'],
    it: ['Vietnam', 'Il Vietnam ha Son Doong, una delle grotte più grandi del mondo.'],
    es: ['Vietnam', 'Vietnam tiene Son Doong, una de las cuevas más grandes del mundo.'],
    'pt-BR': ['Vietnã', 'O Vietnã tem Son Doong, uma das maiores cavernas do mundo.'],
    de: ['Vietnam', 'In Vietnam liegt Son Doong, eine der größten Höhlen der Welt.'],
  },
  turkiye: {
    en: ['Türkiye', 'Istanbul, a city in Türkiye, is on two continents: Europe and Asia.'],
    it: ['Turchia', 'Istanbul, una città della Turchia, sta su due continenti: Europa e Asia.'],
    es: ['Turquía', 'Estambul, una ciudad de Turquía, está en dos continentes: Europa y Asia.'],
    'pt-BR': ['Turquia', 'Istambul, uma cidade da Turquia, fica em dois continentes: Europa e Ásia.'],
    de: ['Türkei', 'Istanbul, eine Stadt in der Türkei, liegt auf zwei Kontinenten: Europa und Asien.'],
  },
  china: {
    en: ['China', 'The Great Wall of China is thousands of kilometers long.'],
    it: ['Cina', 'La Grande Muraglia cinese è lunga migliaia di chilometri.'],
    es: ['China', 'La Gran Muralla China mide miles de kilómetros.'],
    'pt-BR': ['China', 'A Grande Muralha da China tem milhares de quilômetros.'],
    de: ['China', 'Die Chinesische Mauer ist Tausende Kilometer lang.'],
  },
  india: {
    en: ['India', 'India has more people than any other country.'],
    it: ['India', 'L’India ha più abitanti di qualsiasi altro paese.'],
    es: ['India', 'India tiene más habitantes que cualquier otro país.'],
    'pt-BR': ['Índia', 'A Índia tem mais habitantes do que qualquer outro país.'],
    de: ['Indien', 'Indien hat mehr Einwohner als jedes andere Land.'],
  },
  usa: {
    en: ['United States', 'The United States has 50 states, one for each star on its flag.'],
    it: ['Stati Uniti', 'Gli Stati Uniti hanno 50 stati, uno per ogni stella della bandiera.'],
    es: ['Estados Unidos', 'Estados Unidos tiene 50 estados, uno por cada estrella de su bandera.'],
    'pt-BR': ['Estados Unidos', 'Os Estados Unidos têm 50 estados, um para cada estrela da bandeira.'],
    de: ['USA', 'Die USA haben 50 Bundesstaaten, einen für jeden Stern auf der Flagge.'],
  },
  uk: {
    en: ['United Kingdom', 'The United Kingdom is made of England, Scotland, Wales and Northern Ireland.'],
    it: ['Regno Unito', 'Il Regno Unito è fatto di Inghilterra, Scozia, Galles e Irlanda del Nord.'],
    es: ['Reino Unido', 'El Reino Unido está formado por Inglaterra, Escocia, Gales e Irlanda del Norte.'],
    'pt-BR': ['Reino Unido', 'O Reino Unido é formado por Inglaterra, Escócia, País de Gales e Irlanda do Norte.'],
    de: ['Vereinigtes Königreich', 'Das Vereinigte Königreich besteht aus England, Schottland, Wales und Nordirland.'],
  },
  brazil: {
    en: ['Brazil', 'Most of the Amazon rainforest is in Brazil.'],
    it: ['Brasile', 'La maggior parte della foresta amazzonica si trova in Brasile.'],
    es: ['Brasil', 'La mayor parte de la selva amazónica está en Brasil.'],
    'pt-BR': ['Brasil', 'A maior parte da Floresta Amazônica fica no Brasil.'],
    de: ['Brasilien', 'Der größte Teil des Amazonas-Regenwalds liegt in Brasilien.'],
  },
  argentina: {
    en: ['Argentina', 'Argentina has Aconcagua, the tallest mountain in the Americas.'],
    it: ['Argentina', 'In Argentina c’è l’Aconcagua, la montagna più alta delle Americhe.'],
    es: ['Argentina', 'Argentina tiene el Aconcagua, la montaña más alta de América.'],
    'pt-BR': ['Argentina', 'A Argentina tem o Aconcágua, a montanha mais alta das Américas.'],
    de: ['Argentinien', 'In Argentinien steht der Aconcagua, der höchste Berg Amerikas.'],
  },
  jamaica: {
    en: ['Jamaica', 'Jamaica is the home of reggae music.'],
    it: ['Giamaica', 'La Giamaica è la patria della musica reggae.'],
    es: ['Jamaica', 'Jamaica es la cuna de la música reggae.'],
    'pt-BR': ['Jamaica', 'A Jamaica é a terra do reggae.'],
    de: ['Jamaika', 'Jamaika ist die Heimat der Reggae-Musik.'],
  },
  peru: {
    en: ['Peru', 'Machu Picchu, an old Inca city, sits high in the mountains of Peru.'],
    it: ['Perù', 'Machu Picchu, un’antica città inca, si trova in alto sulle montagne del Perù.'],
    es: ['Perú', 'Machu Picchu, una antigua ciudad inca, está en lo alto de las montañas de Perú.'],
    'pt-BR': ['Peru', 'Machu Picchu, uma antiga cidade inca, fica no alto das montanhas do Peru.'],
    de: ['Peru', 'Machu Picchu, eine alte Inkastadt, liegt hoch in den Bergen von Peru.'],
  },
};

const LANGUAGE_COLUMNS = ['en', 'it', 'es', 'pt-BR', 'de'];

function content(language) {
  const strings = {};
  const column = LANGUAGE_COLUMNS.indexOf(language) + 1;
  ANIMALS.forEach((row) => {
    strings[`animal.${row[0]}`] = row[column];
  });
  Object.entries(SPACE).forEach(([key, byLanguage]) => {
    [strings[`space.${key}.name`], strings[`space.${key}.fact`]] = byLanguage[language];
  });
  Object.entries(COUNTRIES).forEach(([key, byLanguage]) => {
    [strings[`country.${key}.name`], strings[`country.${key}.fact`]] = byLanguage[language];
  });
  return strings;
}

addStrings(Object.fromEntries(LANGUAGE_COLUMNS.map((language) => [language, { ...ui[language], ...content(language) }])));
